prod:
  outputs:
    prod:
      dbname: dalgo_warehouse
      host: localhost
      password: 3ivq0txfudg7y
      port: 5432
      schema: prod
      threads: 4
      type: postgres
      user: dalgo_airbyte_user
    dev:
      dbname: dalgo_warehouse
      host: localhost
      password: 3ivq0txfudg7y
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: dalgo_airbyte_user

  target: dev