{{ 
    config(
        materialized='table',
        unique_key='case_id',
        tags=['commcare_extraction', 'sl', 'sl_new_models']
    ) 
}}

with raw_cases as (
    select
        data ->> 'case_id' as case_id,
        COALESCE(data -> 'properties' ->> 'date_of_registration', data -> 'properties' ->> 'date_of_registration_dir') as date_of_registration_raw,
        data -> 'properties' ->> 'pp_unique_id' as pp_unique_id,
        coalesce(
            data -> 'properties' ->> 'participant_full-name_dir',
            data -> 'properties' ->> 'pp_fullname',
            data -> 'properties' ->> 'pp_fullname_dir',
            data -> 'properties' ->> 'name_sp',
            data -> 'properties' ->> 'name_sr',
            data -> 'properties' ->> 'name_tc',
            data -> 'properties' ->> 'name_pl',
            data -> 'properties' ->> 'name_psr',
            data -> 'properties' ->> 'users_fullname',
            data -> 'properties' ->> 'fullname',
            data -> 'properties' ->> 'fullname_csr'
        ) as pp_fullname,
        coalesce(
            data -> 'properties' ->> 'pp_sex',
            data -> 'properties' ->> 'sex_csf',
            data -> 'properties' ->> 'sex_dir',
            data -> 'properties' ->> 'sex_uid',
            data -> 'properties' ->> 'gender_bm',
            data -> 'properties' ->> 'gender_csf',
            data -> 'properties' ->> 'gender_hh_dka'
        ) as gender,
        coalesce(
            data -> 'properties' ->> 'nationality_csf',
            data -> 'properties' ->> 'nationality_dir'
        ) as nationality,
        data -> 'properties' ->> 'kenyan_national_id_number_dir' as kenyan_national_id_number_dir,
        coalesce(
            data -> 'properties' ->> 'county_dir',
            data -> 'properties' ->> 'participants_county_of_residence_dir',
            data -> 'properties' ->> 'pp_shofco_county',
            data -> 'properties' ->> 'county_bm',
            data -> 'properties' ->> 'county_int',
            data -> 'properties' ->> 'coworking_county_csr'
        ) AS county,
        coalesce(
            data -> 'properties' ->> 'pp_shofco_subcounty',
            data -> 'properties' ->> 'subcounty_apprenticeship_provider_apr',
            data -> 'properties' ->> 'subcounty_bm',
            data -> 'properties' ->> 'subcounty_business_bga',
            data -> 'properties' ->> 'subcounty_business_located_bga',
            data -> 'properties' ->> 'subcounty_coworking_site_csf',
            data -> 'properties' ->> 'sub_county_of_institution_ttia',
            data -> 'properties' ->> 'sub-county_of_shofco_site_dir',
            data -> 'properties' ->> 'subcounty_shofco_site_dir',
            data -> 'properties' ->> 'coworking_subcounty_csr'
        ) as subcounty,
        coalesce(
            data -> 'properties' ->> 'pp_ahofco_ward',
            data -> 'properties' ->> 'ward_bm',
            data -> 'properties' ->> 'ward_business_bga',
            data -> 'properties' ->> 'ward_business_located_bga',
            data -> 'properties' ->> 'ward_coworking_site_csf',
            data -> 'properties' ->> 'ward_dc',
            data -> 'properties' ->> 'ward_dir',
            data -> 'properties' ->> 'ward_located_apbl',
            data -> 'properties' ->> 'ward_of_shofco_site_dir',
            data -> 'properties' ->> 'ward_of_the_institution_ttia',
            data -> 'properties' ->> 'ward_shofco_site_dir',
            data -> 'properties' ->> 'coworking_ward_csr'
        ) as ward,
        data -> 'properties' ->> 'coworking_county_csr' as coworking_county_csr,
        data -> 'properties' ->> 'coworking_subcounty_csr' as coworking_subcounty_csr,
        data -> 'properties' ->> 'coworking_ward_csr' as coworking_ward_csr,
        coalesce(
            data -> 'properties' ->> 'primary_phone_number_dir',
            data -> 'properties' ->> 'primary_phone_number_csf'
        ) as primary_phone_number,
        coalesce(
            data -> 'properties' ->> 'is_plwd',
            data -> 'properties' ->> 'is_plwd_csf',
            data -> 'properties' ->> 'is_pwd',
            data -> 'properties' ->> 'is_pwd_tvbl'
        ) as is_pwd,
        data -> 'properties' ->> 'apprenticeship_provider_apr' as apprenticeship_provider_apr,
        data -> 'properties' ->> 'placement_date_apr' as placement_date_apr_raw,
        data -> 'properties' ->> 'grant_amount_bg' as grant_amount_bg,
        data -> 'properties' ->> 'date_grant_allocated_bg' as date_grant_allocated_bg_raw,
        data -> 'properties' ->> 'digital_literacy_dl' as digital_literacy_dl,
        data -> 'properties' ->> 'start_date_dl' as start_date_dl_raw,
        data -> 'properties' ->> 'advanced_it_start_date_dl' as advanced_it_start_date_dl_raw,
        data -> 'properties' ->> 'advanced_it_completion_date_dl' as advanced_it_completion_date_dl_raw,
        data -> 'properties' ->> 'completion_date_dl' as completion_date_dl_raw,
        data -> 'properties' ->> 'final_exams_tc' as final_exams_tc,
        data -> 'properties' ->> 'start_date_ent' as start_date_ent_raw,
        data -> 'properties' ->> 'completion_date_ent' as completion_date_ent_raw,
        data -> 'properties' ->> 'start_date_int' as start_date_int_raw,
        data -> 'properties' ->> 'completion_date_int' as completion_date_int_raw,
        data -> 'properties' ->> 'income_on_average_pl' as income_on_average_pl,
        data -> 'properties' ->> 'placement_opportunity_pl' as placement_opportunity_pl,
        data -> 'properties' ->> 'date_first_visit_bm' as date_first_visit_bm_raw,
        data -> 'properties' ->> 'date_of_second_visit_bm' as date_of_second_visit_bm_raw,
        data -> 'properties' ->> 'date_of_visit_csf' as date_of_visit_csf_raw,
        data -> 'properties' ->> 'date_of_visit_csr' as date_of_visit_csr_raw,
        data -> 'properties' ->> 'how_many_csf' as how_many_csf,
        data -> 'properties' ->> 'time_in_csf' as time_in_csf,
        data -> 'properties' ->> 'time_in_csr' as time_in_csr,
        data -> 'properties' ->> 'time_out_csf' as time_out_csf,
        data -> 'properties' ->> 'time_out_csr' as time_out_csr,
        data -> 'properties' ->> 'using_coworking_for_a_living_csr' as using_coworking_for_a_living_csr,
        data -> 'properties' ->> 'using_coworking_to_earn_a_living_csf' as using_coworking_to_earn_a_living_csf,
        data -> 'properties' ->> 'what_visitor_is_using_csf' as what_visitor_is_using_csf,
        data -> 'properties' ->> 'what_visitor_is_using_csr' as what_visitor_is_using_csr,
        data -> 'properties' ->> 'purpose_for_using_csf' as purpose_for_using_csf,
        data -> 'properties' ->> 'coworking_space_facility' as coworking_space_facility,
        data -> 'properties' ->> 'swep_handcraft_center-hc' as swep_handcraft_center_hc,
        data -> 'properties' ->> 'start_date_hc' as start_date_hc_raw,
        data -> 'properties' ->> 'completion_date_hc' as completion_date_hc_raw,
        coalesce(
            data -> 'properties' ->> 'handcraft_training_type_hc',
            data -> 'properties' ->> 'handcraft_training_type_sr'
        ) as handcraft_training_type_hc,
        data -> 'properties' ->> 'swep-iga-center-iga' as swep_iga_center_iga,
        data -> 'properties' ->> 'start_date_iga' as start_date_iga_raw,
        data -> 'properties' ->> 'completion_date_iga' as completion_date_iga_raw,
        data -> 'properties' ->> 'training_type_iga' as training_type_iga,
        data -> 'properties' ->> 'swep_tailoring_center_st' as swep_tailoring_center_st,
        data -> 'properties' ->> 'start_date_of_training_st' as start_date_of_training_st_raw,
        data -> 'properties' ->> 'expected_end_date_of_training_st' as expected_end_date_of_training_st_raw,
        coalesce(
            data -> 'properties' ->> 'training_session_st',
            data -> 'properties' ->> 'training_session_sr'
        ) as training_session_st,
        data -> 'properties' ->> 'name_of_institution_tvet' as name_of_institution_tvet,
        data -> 'properties' ->> 'course_enrolled_tvet' as course_enrolled_tvet,
        data -> 'properties' ->> 'start_date_tvet' as start_date_tvet_raw,
        coalesce(
            data -> 'properties' ->> 'nita_exams',
            data -> 'properties' ->> 'nita_exams_tc'
        ) as nita_exams
    from {{ source('staging_sl_test_missing', 'zzz_case') }}
    where data -> 'properties' ->> 'case_type' = 'sl_new'
),
prepared_cases as (
select
    case_id,
        {{ validate_date('date_of_registration_raw') }} as date_of_registration,
        pp_unique_id,
        pp_fullname,
        gender,
        nationality,
        kenyan_national_id_number_dir,
        county,
        subcounty,
        ward,
        coworking_county_csr,
        coworking_subcounty_csr,
        coworking_ward_csr,
        primary_phone_number,
        right(primary_phone_number, 8) as phone_last_8_digits,
        is_pwd,
        apprenticeship_provider_apr,
        {{ validate_date('placement_date_apr_raw') }} as placement_date_apr,
        grant_amount_bg,
        {{ validate_date('date_grant_allocated_bg_raw') }} as date_grant_allocated_bg,
        digital_literacy_dl,
        {{ validate_date('start_date_dl_raw') }} as start_date_dl,
        {{ validate_date('advanced_it_start_date_dl_raw') }} as advanced_it_start_date_dl,
        {{ validate_date('advanced_it_completion_date_dl_raw') }} as advanced_it_completion_date_dl,
        {{ validate_date('completion_date_dl_raw') }} as completion_date_dl,
        final_exams_tc,
        {{ validate_date('start_date_ent_raw') }} as start_date_ent,
        {{ validate_date('completion_date_ent_raw') }} as completion_date_ent,
        {{ validate_date('start_date_int_raw') }} as start_date_int,
        {{ validate_date('completion_date_int_raw') }} as completion_date_int,
        income_on_average_pl,
        placement_opportunity_pl,
        {{ validate_date('date_first_visit_bm_raw') }} as date_first_visit_bm,
        {{ validate_date('date_of_second_visit_bm_raw') }} as date_of_second_visit_bm,
        {{ validate_date('date_of_visit_csf_raw') }} as date_of_visit_csf,
        {{ validate_date('date_of_visit_csr_raw') }} as date_of_visit_csr,
        how_many_csf,
        time_in_csf,
        time_in_csr,
        time_out_csf,
        time_out_csr,
        using_coworking_for_a_living_csr,
        using_coworking_to_earn_a_living_csf,
        what_visitor_is_using_csf,
        what_visitor_is_using_csr,
        purpose_for_using_csf,
        coworking_space_facility,
        swep_handcraft_center_hc,
        {{ validate_date('start_date_hc_raw') }} as start_date_hc,
        {{ validate_date('completion_date_hc_raw') }} as completion_date_hc,
        handcraft_training_type_hc,
        swep_iga_center_iga,
        {{ validate_date('start_date_iga_raw') }} as start_date_iga,
        {{ validate_date('completion_date_iga_raw') }} as completion_date_iga,
        training_type_iga,
        swep_tailoring_center_st,
        {{ validate_date('start_date_of_training_st_raw') }} as start_date_of_training_st,
        {{ validate_date('expected_end_date_of_training_st_raw') }} as expected_end_date_of_training_st,
        training_session_st,
        name_of_institution_tvet,
        course_enrolled_tvet,
        {{ validate_date('start_date_tvet_raw') }} as start_date_tvet,
        nita_exams,
        lower(trim(pp_unique_id)) as norm_pp_unique_id,
        regexp_replace(lower(coalesce(pp_fullname, '')), '\s+', ' ', 'g') as norm_pp_fullname,
        lower(trim(kenyan_national_id_number_dir)) as norm_kenyan_id,
        lower(trim(county)) as norm_county
    from raw_cases
),
deduplicated_cases as (
    select
        min(nullif(trim(case_id), '')) as case_id,
        max(date_of_registration) as date_of_registration,
        max(nullif(trim(pp_unique_id), '')) as pp_unique_id,
        max(nullif(trim(pp_fullname), '')) as pp_fullname,
        max(nullif(trim(kenyan_national_id_number_dir), '')) as kenyan_national_id_number_dir,
        max(nullif(trim(gender), '')) as gender,
        max(nullif(trim(nationality), '')) as nationality,
        max(nullif(trim(county), '')) as county,
        max(nullif(trim(subcounty), '')) as subcounty,
        max(nullif(trim(ward), '')) as ward,
        max(nullif(trim(coworking_county_csr), '')) as coworking_county_csr,
        max(nullif(trim(coworking_subcounty_csr), '')) as coworking_subcounty_csr,
        max(nullif(trim(coworking_ward_csr), '')) as coworking_ward_csr,
        max(nullif(trim(primary_phone_number), '')) as primary_phone_number,
        max(nullif(trim(phone_last_8_digits), '')) as phone_last_8_digits,
        CASE
            WHEN max(CASE WHEN lower(nullif(trim(is_pwd), '')) = 'yes' THEN 1 ELSE 0 END) = 1
                THEN 'yes'
            ELSE max(nullif(trim(is_pwd), ''))
        END as is_pwd,
        max(nullif(trim(apprenticeship_provider_apr), '')) as apprenticeship_provider_apr,
        max(placement_date_apr) as placement_date_apr,
        max(nullif(trim(grant_amount_bg), '')) as grant_amount_bg,
        max(date_grant_allocated_bg) as date_grant_allocated_bg,
        max(nullif(trim(digital_literacy_dl), '')) as digital_literacy_dl,
        max(start_date_dl) as start_date_dl,
        max(advanced_it_start_date_dl) as advanced_it_start_date_dl,
        max(advanced_it_completion_date_dl) as advanced_it_completion_date_dl,
        max(completion_date_dl) as completion_date_dl,
        max(nullif(trim(final_exams_tc), '')) as final_exams_tc,
        max(start_date_ent) as start_date_ent,
        max(completion_date_ent) as completion_date_ent,
        max(start_date_int) as start_date_int,
        max(completion_date_int) as completion_date_int,
        max(nullif(trim(income_on_average_pl), '')) as income_on_average_pl,
        max(nullif(trim(placement_opportunity_pl), '')) as placement_opportunity_pl,
        max(date_first_visit_bm) as date_first_visit_bm,
        max(date_of_second_visit_bm) as date_of_second_visit_bm,
        max(date_of_visit_csf) as date_of_visit_csf,
        max(date_of_visit_csr) as date_of_visit_csr,
        max(nullif(trim(how_many_csf), '')) as how_many_csf,
        max(nullif(trim(time_in_csf), '')) as time_in_csf,
        max(nullif(trim(time_in_csr), '')) as time_in_csr,
        max(nullif(trim(time_out_csf), '')) as time_out_csf,
        max(nullif(trim(time_out_csr), '')) as time_out_csr,
        max(nullif(trim(using_coworking_for_a_living_csr), '')) as using_coworking_for_a_living_csr,
        max(nullif(trim(using_coworking_to_earn_a_living_csf), '')) as using_coworking_to_earn_a_living_csf,
        max(nullif(trim(what_visitor_is_using_csf), '')) as what_visitor_is_using_csf,
        max(nullif(trim(what_visitor_is_using_csr), '')) as what_visitor_is_using_csr,
        max(nullif(trim(purpose_for_using_csf), '')) as purpose_for_using_csf,
        max(nullif(trim(coworking_space_facility), '')) as coworking_space_facility,
        max(nullif(trim(swep_handcraft_center_hc), '')) as swep_handcraft_center_hc,
        max(start_date_hc) as start_date_hc,
        max(completion_date_hc) as completion_date_hc,
        max(nullif(trim(handcraft_training_type_hc), '')) as handcraft_training_type_hc,
        max(nullif(trim(swep_iga_center_iga), '')) as swep_iga_center_iga,
        max(start_date_iga) as start_date_iga,
        max(completion_date_iga) as completion_date_iga,
        max(nullif(trim(training_type_iga), '')) as training_type_iga,
        max(nullif(trim(swep_tailoring_center_st), '')) as swep_tailoring_center_st,
        max(start_date_of_training_st) as start_date_of_training_st,
        max(expected_end_date_of_training_st) as expected_end_date_of_training_st,
        max(nullif(trim(training_session_st), '')) as training_session_st,
        max(nullif(trim(name_of_institution_tvet), '')) as name_of_institution_tvet,
        max(nullif(trim(course_enrolled_tvet), '')) as course_enrolled_tvet,
        max(start_date_tvet) as start_date_tvet,
        CASE
            WHEN max(CASE WHEN lower(nullif(trim(nita_exams), '')) = 'yes' THEN 1 ELSE 0 END) = 1
                THEN 'yes'
            ELSE max(nullif(trim(nita_exams), ''))
        END as nita_exams
    from prepared_cases
    group by
        norm_pp_unique_id,
        norm_pp_fullname,
        norm_kenyan_id,
        phone_last_8_digits,
        norm_county
)

select
    case_id,
    date_of_registration,
    pp_unique_id,
    pp_fullname,
    gender,
    nationality,
    kenyan_national_id_number_dir,
    case
        when county is null or trim(county) = '' then null
        else initcap(regexp_replace(county, '[\\s_/-]+', '', 'g'))
    end as county,
    case
        when subcounty is null or trim(subcounty) = '' then null
        else initcap(regexp_replace(subcounty, '[\\s_/-]+', '', 'g'))
    end as subcounty,
    case
        when ward is null or trim(ward) = '' then null
        else initcap(regexp_replace(ward, '[\\s_/-]+', '', 'g'))
    end as ward,
    coworking_county_csr,
    coworking_subcounty_csr,
    coworking_ward_csr,
    primary_phone_number,
    phone_last_8_digits,
    case when is_pwd is null or trim(is_pwd) = '' then null else initcap(is_pwd) end as is_pwd,
    apprenticeship_provider_apr,
    placement_date_apr,
    grant_amount_bg,
    date_grant_allocated_bg,
    digital_literacy_dl,
    start_date_dl,
    advanced_it_start_date_dl,
    advanced_it_completion_date_dl,
    completion_date_dl,
    final_exams_tc,
    start_date_ent,
    completion_date_ent,
    start_date_int,
    completion_date_int,
    income_on_average_pl,
    placement_opportunity_pl,
    date_first_visit_bm,
    date_of_second_visit_bm,
    date_of_visit_csf,
    date_of_visit_csr,
    how_many_csf,
    time_in_csf,
    time_in_csr,
    time_out_csf,
    time_out_csr,
    using_coworking_for_a_living_csr,
    using_coworking_to_earn_a_living_csf,
    what_visitor_is_using_csf,
    what_visitor_is_using_csr,
    purpose_for_using_csf,
    coworking_space_facility,
    swep_handcraft_center_hc,
    start_date_hc,
    completion_date_hc,
    handcraft_training_type_hc,
    swep_iga_center_iga,
    start_date_iga,
    completion_date_iga,
    training_type_iga,
    swep_tailoring_center_st,
    start_date_of_training_st,
    expected_end_date_of_training_st,
    training_session_st,
    name_of_institution_tvet,
    course_enrolled_tvet,
    start_date_tvet,
    nita_exams
from deduplicated_cases
