{{ 
    config(
        materialized='incremental',
        unique_key='case_id',
        alias='sl_case_table',
        tags=['commcare_extraction', 'sl', 'sl_case_table'],
        enabled=False
    ) 
}}

SELECT 
    -- Base case fields
    data ->> 'case_id' as case_id,
    data ->> 'closed' as closed,
    data ->> 'closed_by' as closed_by,
    data ->> 'date_closed' as date_closed,
    data ->> 'date_modified' as date_modified,
    data -> 'properties' ->> 'case_name' as case_name,
    data -> 'properties' ->> 'case_type' as case_type,
    
    -- data ->> 'domain' as domain,
    data ->> 'id' as id,
    data ->> 'indexed_on' as indexed_on,
    data ->> 'user_id' as user_id,
    
    -- Indices fields
    data -> 'indices' -> 'parent' ->> 'case_id' as indices_parent_case_id,
    data -> 'indices' -> 'parent' ->> 'case_type' as indices_parent_case_type,
    data -> 'indices' -> 'parent' ->> 'relationship' as indices_parent_relationship,

    -- Demographic fields
    COALESCE(data -> 'properties' ->> 'pp_sex', data -> 'properties' ->> 'sex_csf', data -> 'properties' ->> 'sex_dir', data -> 'properties' ->> 'sex_uid', data -> 'properties' ->> 'gender_bm', data -> 'properties' ->> 'gender_csf', data -> 'properties' ->> 'gender_hh_dka') as sex,
    COALESCE(data -> 'properties' ->> 'pp_age', data -> 'properties' ->> 'age_in_years', data -> 'properties' ->> 'age_in_years_csf', data -> 'properties' ->> 'age_in_years_dir') as age,
    COALESCE(data -> 'properties' ->> 'date_of_birth_bm', data -> 'properties' ->> 'date_of_birth_csf', data -> 'properties' ->> 'date_of_birth_dir', data -> 'properties' ->> 'date_of_birth_dki') as date_of_birth,
    data -> 'properties' ->> 'pp_ahofco_ward' as pp_ahofco_ward,
    COALESCE(data -> 'properties' ->> 'participant_full-name_dir', data -> 'properties' ->> 'pp_fullname', data -> 'properties' ->> 'name_sp', data -> 'properties' ->> 'name_sr', data -> 'properties' ->> 'name_tc', data -> 'properties' ->> 'name_pl', data -> 'properties' ->> 'name_psr') as pp_fullname,
    COALESCE(data -> 'properties' ->> 'county_dir', data -> 'properties' ->> 'participants_county_of_residence_dir', data -> 'properties' ->> 'pp_shofco_county', data -> 'properties' ->> 'county_bm', data -> 'properties' ->> 'county_int') AS county,
    data -> 'properties' ->> 'pp_shofco_subcounty' as pp_shofco_subcounty,
    data -> 'properties' ->> 'pp_unique_id' as pp_unique_id,
    COALESCE(data -> 'properties' ->> 'Second_Name_bg', data -> 'properties' ->> 'second_name_csf', data -> 'properties' ->> 'second_name_dir', data -> 'properties' ->> 'Second_Name_dir', data -> 'properties' ->> 'Second_Name_sp') as second_name,
    COALESCE(data -> 'properties' ->> 'children_in_need_daycare_uf', data -> 'properties' ->> 'children_inneed_daycare_uf',  data -> 'properties' ->> 'children_in_need_of_daycare_support_sr') as children_in_need_of_daycare_support,
    COALESCE(data -> 'properties' ->> 'children_under_4', data -> 'properties' ->> 'children_under_4_sr', data -> 'properties' ->> 'children_under_4_uf') as children_under_4,
    COALESCE(data -> 'properties' ->> 'children_with_disabilities_sr', data -> 'properties' ->> 'children_withdisabilities_uf') as children_with_disabilities,
    COALESCE(data -> 'properties' ->> 'citizenship_dir', data -> 'properties' ->> 'participants_citzenship_dir') AS citizenship,
    data -> 'properties' ->> 'participant_program_int' as participant_program_int,
    data -> 'properties' ->> 'participant_program_pl' as participant_program_pl,
    data -> 'properties' ->> 'participants_constituency_of_residence_dir' as participants_constituency_of_residence_dir,
    data -> 'properties' ->> 'participants_level_of_education_dir' as participants_level_of_education_dir,
    data -> 'properties' ->> 'participants_nationality_dir' as participants_nationality_dir,
    data -> 'properties' ->> 'participants_program_sr' as participants_program_sr,
    data -> 'properties' ->> 'participants_refugee_type_dir' as participants_refugee_type_dir,
    data -> 'properties' ->> 'participants_type_of_work_sr' as participants_type_of_work_sr,
    data -> 'properties' ->> 'participated_in_swep_trainings_bga' as participated_in_swep_trainings_bga,
    COALESCE(data -> 'properties' ->> 'first_name_bg', data -> 'properties' ->> 'first_name_csf', data -> 'properties' ->> 'first_name_dir', data -> 'properties' ->> 'first_name_sp') as first_name,
    data -> 'properties' ->> 'is_mother_csf' as is_mother_csf,
    COALESCE(data -> 'properties' ->> 'is_plwd', data -> 'properties' ->> 'is_plwd_csf', data -> 'properties' ->> 'is_pwd', data -> 'properties' ->> 'is_pwd_tvbl') as is_pwd,
    COALESCE(data -> 'properties' ->> 'nationality_csf', data -> 'properties' ->> 'nationality_dir') as nationality,
    data -> 'properties' ->> 'county_business_bga' as county_business_bga,
    data -> 'properties' ->> 'county_business_located_bga' as county_business_located_bga,
    data -> 'properties' ->> 'county_coworking_site_csf' as county_coworking_site_csf,
    data -> 'properties' ->> 'county_institution_dc' as county_institution_dc,
    data -> 'properties' ->> 'county_located_apbl' as county_located_apbl,
    data -> 'properties' ->> 'county_of_institution_ttia' as county_of_institution_ttia,
    data -> 'properties' ->> 'county_of_job_transition_pl' as county_of_job_transition_pl,
    data -> 'properties' ->> 'county_of_job_transition_placement' as county_of_job_transition_placement,
    data -> 'properties' ->> 'county_of_preference_sr' as county_of_preference_sr,
    data -> 'properties' ->> 'county_of_residence_dki' as county_of_residence_dki,
    data -> 'properties' ->> 'county_of_shofco_site_dir' as county_of_shofco_site_dir,
    data -> 'properties' ->> 'county_placed_tvet' as county_placed_tvet,
    data -> 'properties' ->> 'county_placed_tvet_uf' as county_placed_tvet_uf,
    data -> 'properties' ->> 'county_shofco_site_dir' as county_shofco_site_dir,
    data -> 'properties' ->> 'coworking_county_csr' as coworking_county_csr,
    data -> 'properties' ->> 'country' as country,
    data -> 'properties' ->> 'name_consent' as name_consent,
    data -> 'properties' ->> 'name_csf' as name_csf,
    data -> 'properties' ->> 'MPESA_full-name_sp' as MPESA_full_name_sp,
    data -> 'properties' ->> 'visitor_fullname_csf' as visitor_fullname_csf,
    data -> 'properties' ->> 'ward_bm' as ward_bm,
    data -> 'properties' ->> 'ward_business_bga' as ward_business_bga,
    data -> 'properties' ->> 'ward_business_located_bga' as ward_business_located_bga,
    data -> 'properties' ->> 'ward_coworking_site_csf' as ward_coworking_site_csf,
    data -> 'properties' ->> 'ward_dc' as ward_dc,
    data -> 'properties' ->> 'ward_dir' as ward_dir,
    data -> 'properties' ->> 'ward_located_apbl' as ward_located_apbl,
    data -> 'properties' ->> 'ward_of_shofco_site_dir' as ward_of_shofco_site_dir,
    data -> 'properties' ->> 'ward_of_the_institution_ttia' as ward_of_the_institution_ttia,
    data -> 'properties' ->> 'ward_shofco_site_dir' as ward_shofco_site_dir,
    data -> 'properties' ->> 'visitors_nationality_csf' as visitors_nationality_csf,
    data -> 'properties' ->> 'any_children_dc' as any_children_dc,
    data -> 'properties' ->> 'any_children_inneed_of_daycare_dc' as any_children_inneed_of_daycare_dc,
    data -> 'properties' ->> 'any_children_with_disabilities_sr' as any_children_with_disabilities_sr,
    data -> 'properties' ->> 'contact_of_the_mentee_bm' as contact_of_the_mentee_bm,
    data -> 'properties' ->> 'contact_phone_number' as contact_phone_number,
    data -> 'properties' ->> 'coworking_subcounty_csr' as coworking_subcounty_csr,
    data -> 'properties' ->> 'coworking_ward_csr' as coworking_ward_csr,

    -- Courses Info
    data -> 'properties' ->> 'total_completed' as total_completed,
    data -> 'properties' ->> 'total_completed_courses' as total_completed_courses,
    data -> 'properties' ->> 'total_dropped' as total_dropped,
    data -> 'properties' ->> 'total_dropped_courses' as total_dropped_courses,
    data -> 'properties' ->> 'course_completed' as course_completed,
    data -> 'properties' ->> 'course_enrolled_sr' as course_enrolled_sr,
    data -> 'properties' ->> 'course_enrolled_tvet' as course_enrolled_tvet,
    data -> 'properties' ->> 'courses_completed' as courses_completed,
    data -> 'properties' ->> 'course_under_review' as course_under_review,
    data -> 'properties' ->> 'course_undertaking_dc' as course_undertaking_dc,
    data -> 'properties' ->> 'courses_having_internal_certifications_ttia' as courses_having_internal_certifications_ttia,
    data -> 'properties' ->> 'completed_courses' as completed_courses,
    data -> 'properties' ->> 'completed_courses_list' as completed_courses_list,
    data -> 'properties' ->> 'completed_training' as completed_training,
    data -> 'properties' ->> 'completed_training_tc' as completed_training_tc,
    data -> 'properties' ->> 'completed_upskilling_uf' as completed_upskilling_uf,
    data -> 'properties' ->> 'complete_training_bga' as complete_training_bga,
    data -> 'properties' ->> 'completion_date_apr' as completion_date_apr,
    data -> 'properties' ->> 'completion_date_dl' as completion_date_dl,
    data -> 'properties' ->> 'completion_date_ent' as completion_date_ent,
    data -> 'properties' ->> 'completion_date_hc' as completion_date_hc,
    data -> 'properties' ->> 'Completion_date_iga' as Completion_date_iga,
    data -> 'properties' ->> 'completion_date_int' as completion_date_int,
    data -> 'properties' ->> 'completion_date_sr' as completion_date_sr,
    data -> 'properties' ->> 'completion_date_tvet' as completion_date_tvet,
    data -> 'properties' ->> 'completion_tvet' as completion_tvet,
    data -> 'properties' ->> 'alternative_contact_apbl' as alternative_contact_apbl,
    data -> 'properties' ->> 'alternative_contact_bm' as alternative_contact_bm,
    data -> 'properties' ->> 'alternative_phone_number_dir' as alternative_phone_number_dir,

    -- ALL Properties fields (every single one from your list)
    data -> 'properties' ->> 'able_to_accomodate_refugees_ttia' as able_to_accomodate_refugees_ttia,
    data -> 'properties' ->> 'able_to_afford_the_daycare_dc' as able_to_afford_the_daycare_dc,
    data -> 'properties' ->> 'able_to_pay_the_tuition_fee_tvbl' as able_to_pay_the_tuition_fee_tvbl,
    data -> 'properties' ->> 'able_to_take_pwd_students_ttia' as able_to_take_pwd_students_ttia,
    data -> 'properties' ->> 'activity_dka' as activity_dka,
    data -> 'properties' ->> 'activity_enrolled_on_sr' as activity_enrolled_on_sr,
    data -> 'properties' ->> 'activity_participant_is_enrolled_on_sr' as activity_participant_is_enrolled_on_sr,
    data -> 'properties' ->> 'activity_the_beneficiary_is_participating_dki' as activity_the_beneficiary_is_participating_dki,
    data -> 'properties' ->> 'additional_comments_dir' as additional_comments_dir,
    data -> 'properties' ->> 'additional_details_relevant_apbl' as additional_details_relevant_apbl,
    data -> 'properties' ->> 'additional_informationcomments_dc' as additional_informationcomments_dc,
    data -> 'properties' ->> 'additional_information_ttia' as additional_information_ttia,
    data -> 'properties' ->> 'additional_support_uf' as additional_support_uf,
    data -> 'properties' ->> 'additional_training_interested_sr' as additional_training_interested_sr,
    data -> 'properties' ->> 'additional_training_service_interested_in_the_program_sr' as additional_training_service_interested_in_the_program_sr,
    data -> 'properties' ->> 'advanced_it_completion_date_dl' as advanced_it_completion_date_dl,
    data -> 'properties' ->> 'advanced_it_course_of_interest_dir' as advanced_it_course_of_interest_dir,
    data -> 'properties' ->> 'advanced_it_dl' as advanced_it_dl,
    data -> 'properties' ->> 'advanced_it_start_date_dl' as advanced_it_start_date_dl,
    data -> 'properties' ->> 'agreed_timeline_to_implement_solutions_bm' as agreed_timeline_to_implement_solutions_bm,
    data -> 'properties' ->> 'agreed_timeline_to_implement_the_solutions_bm' as agreed_timeline_to_implement_the_solutions_bm,
    data -> 'properties' ->> 'amount_per_piece_sp' as amount_per_piece_sp,
    data -> 'properties' ->> 'amount_requested_bg' as amount_requested_bg,
    data -> 'properties' ->> 'another_branch_apbl' as another_branch_apbl,
    data -> 'properties' ->> 'any_business_grant_bg' as any_business_grant_bg,
    data -> 'properties' ->> 'any_formal_education_dir' as any_formal_education_dir,
    data -> 'properties' ->> 'any_other_comment_tvbl' as any_other_comment_tvbl,
    data -> 'properties' ->> 'apprenticeship_provider_apr' as apprenticeship_provider_apr,
    data -> 'properties' ->> 'apprenticeship_provider_contact_apr' as apprenticeship_provider_contact_apr,
    data -> 'properties' ->> 'apprenticeship_provider_dka' as apprenticeship_provider_dka,
    data -> 'properties' ->> 'areas_of_improvement_tvbl' as areas_of_improvement_tvbl,
    data -> 'properties' ->> 'areas_of_interest_within_technology_sector_tvet' as areas_of_interest_within_technology_sector_tvet,
    data -> 'properties' ->> 'areas_the_mentee_needs_further_sessions_bm' as areas_the_mentee_needs_further_sessions_bm,
    data -> 'properties' ->> 'are_other_interests_met_tvbl' as are_other_interests_met_tvbl,
    data -> 'properties' ->> 'are_to_provide_service_apbl' as are_to_provide_service_apbl,
    data -> 'properties' ->> 'are_you_a_parent_dki' as are_you_a_parent_dki,
    data -> 'properties' ->> 'are_you_a_person_living_with_disability_bm' as are_you_a_person_living_with_disability_bm,
    data -> 'properties' ->> 'are_you_with_disability_dki' as are_you_with_disability_dki,
    data -> 'properties' ->> 'asylum_pass_number_csf' as asylum_pass_number_csf,
    data -> 'properties' ->> 'asylum_pass_number_dir' as asylum_pass_number_dir,
    data -> 'properties' ->> 'asylum_pass_registration_number_dir' as asylum_pass_registration_number_dir,
    data -> 'properties' ->> 'average_monthly_profit_bga' as average_monthly_profit_bga,
    data -> 'properties' ->> 'average_monthly_salary_sr' as average_monthly_salary_sr,
    data -> 'properties' ->> 'average_monthly_salary_wage_sr' as average_monthly_salary_wage_sr,
    data -> 'properties' ->> 'average_weekly_customers_apbl' as average_weekly_customers_apbl,
    data -> 'properties' ->> 'bank_account_active_lenght_apbl' as bank_account_active_lenght_apbl,
    data -> 'properties' ->> 'beneficiary_MPESA_full-name_bg' as beneficiary_MPESA_full_name_bg,
    data -> 'properties' ->> 'benifited_from_shofco_bga' as benifited_from_shofco_bga,
    data -> 'properties' ->> 'business_applicant_eligible_for_grant_bga' as business_applicant_eligible_for_grant_bga,
    data -> 'properties' ->> 'business_costs_before_setting_prices_bm' as business_costs_before_setting_prices_bm,
    data -> 'properties' ->> 'business_do_you_intend_to_start_up_bga' as business_do_you_intend_to_start_up_bga,
    data -> 'properties' ->> 'business_gap_or_challenge_apbl' as business_gap_or_challenge_apbl,
    COALESCE(data -> 'properties' ->> 'business_location_apbl', data -> 'properties' ->> 'business_location_apr', data -> 'properties' ->> 'business_location_bg', data -> 'properties' ->> 'business_location_bm', data -> 'properties' ->> 'business_location_pl', data -> 'properties' ->> 'business_location_sr') as business_location,
    COALESCE(data -> 'properties' ->> 'business_permit_apbl', data -> 'properties' ->> 'business_permit__apbl') as business_permit,
    data -> 'properties' ->> 'business_potential_bga' as business_potential_bga,
    data -> 'properties' ->> 'business_records_the_mentee_keeps_bm' as business_records_the_mentee_keeps_bm,
    data -> 'properties' ->> 'business_type_bg' as business_type_bg,
    data -> 'properties' ->> 'bus_location_bm' as bus_location_bm,
    data -> 'properties' ->> 'calculation_date_consent' as calculation_date_consent,
    data -> 'properties' ->> 'can_start_anytime_apbl' as can_start_anytime_apbl,
    data -> 'properties' ->> 'cash_to_buy_new_stock_bm' as cash_to_buy_new_stock_bm,
    data -> 'properties' ->> 'Category_of_Business_bga' as Category_of_Business_bga,
    data -> 'properties' ->> 'center_manager_name_ttia' as center_manager_name_ttia,
    data -> 'properties' ->> 'certifications_achieved_pl' as certifications_achieved_pl,
    data -> 'properties' ->> 'certification_sr' as certification_sr,
    data -> 'properties' ->> 'certification_type_sr' as certification_type_sr,
    data -> 'properties' ->> 'certification_upon_completion_apbl' as certification_upon_completion_apbl,
    COALESCE(data -> 'properties' ->> 'challenges_accessing_personal_hygiene_items_sr', data -> 'properties' ->> 'challenges_accessing_personal_hygiene_items_uf') as challenges_accessing_personal_hygiene_items,
    data -> 'properties' ->> 'challenges_encountered_affecting_studies_tvbl' as challenges_encountered_affecting_studies_tvbl,
    data -> 'properties' ->> 'challenges_encountered_outside_tvbl' as challenges_encountered_outside_tvbl,
    data -> 'properties' ->> 'challenges_mentee_is_facing_bm' as challenges_mentee_is_facing_bm,
    data -> 'properties' ->> 'challenges_mentee_is_facing_running_business_bm' as challenges_mentee_is_facing_running_business_bm,
    data -> 'properties' ->> 'common_training_course_dir' as common_training_course_dir,
    COALESCE(data -> 'properties' ->> 'common_training', data -> 'properties' ->> 'common_training_dir', data -> 'properties' ->> 'common_training_dr') as common_training,
    data -> 'properties' ->> 'common_training_participant_interested_dir' as common_training_participant_interested_dir,
    data -> 'properties' ->> 'complementary_courses_offered_ttia' as complementary_courses_offered_ttia,
    data -> 'properties' ->> 'component_of_service_to_be_upskilled' as component_of_service_to_be_upskilled,
    data -> 'properties' ->> 'computer_certification_sr' as computer_certification_sr,
    data -> 'properties' ->> 'computer_literacy_and_certification_sr' as computer_literacy_and_certification_sr,
    data -> 'properties' ->> 'computer_literate_sr' as computer_literate_sr,
    data -> 'properties' ->> 'computer-packages_completion_date_dl' as computer_packages_completion_date_dl,
    data -> 'properties' ->> 'computer_packages_start_date_dl' as computer_packages_start_date_dl,
    data -> 'properties' ->> 'confidence_to_find_employment' as confidence_to_find_employment,
    data -> 'properties' ->> 'confidence_to_find_employment_tc' as confidence_to_find_employment_tc,
    data -> 'properties' ->> 'confidence_to_get_job_tvbl' as confidence_to_get_job_tvbl,
    data -> 'properties' ->> 'Consent' as Consent,
    data -> 'properties' ->> 'constituency_dir' as constituency_dir,
    data -> 'properties' ->> 'contact_of_deputy_manager_ttia' as contact_of_deputy_manager_ttia,
    COALESCE(data -> 'properties' ->> 'contact_of_mentor_bm', data -> 'properties' ->> 'contact_of_the_mentor_bm') as contact_of_mentor_bm,
    data -> 'properties' ->> 'contact_phone_number_is_verified' as contact_phone_number_is_verified,
    data -> 'properties' ->> 'count_casedb' as count_casedb,
    data -> 'properties' ->> 'currently_engaged_in_anywork_dc' as currently_engaged_in_anywork_dc,
    data -> 'properties' ->> 'currently_engaged_in_any_work_tvbl' as currently_engaged_in_any_work_tvbl,
    data -> 'properties' ->> 'current_student_number_of_course_ttia' as current_student_number_of_course_ttia,
    data -> 'properties' ->> 'date_consent' as date_consent,
    data -> 'properties' ->> 'date_dignity_kit_was_issued_dki' as date_dignity_kit_was_issued_dki,
    data -> 'properties' ->> 'date_existing_and_trainings_started_ttia' as date_existing_and_trainings_started_ttia,
    data -> 'properties' ->> 'date_first_visit_bm' as date_first_visit_bm,
    data -> 'properties' ->> 'date_grant_allocated_bg' as date_grant_allocated_bg,
    data -> 'properties' ->> 'date_of_first_visit_bm' as date_of_first_visit_bm,
    data -> 'properties' ->> 'date_of_issuance_dki' as date_of_issuance_dki,
    data -> 'properties' ->> 'date_of_production_sp' as date_of_production_sp,
    COALESCE(data -> 'properties' ->> 'date_of_registration', data -> 'properties' ->> 'date_of_registration_dir') as date_of_registration,
    data -> 'properties' ->> 'date_of_sale_ses' as date_of_sale_ses,
    data -> 'properties' ->> 'date_of_second_visit_bm' as date_of_second_visit_bm,
    data -> 'properties' ->> 'date_of_the_second_visit_bm' as date_of_the_second_visit_bm,
    data -> 'properties' ->> 'date_of_visit_csf' as date_of_visit_csf,
    data -> 'properties' ->> 'date_of_visit_csr' as date_of_visit_csr,
    data -> 'properties' ->> 'date_opened' as date_opened,
    data -> 'properties' ->> 'daycare_support_needed_uf' as daycare_support_needed_uf,
    COALESCE(data -> 'properties' ->> 'days_eaten_only_one_meal_sr', data -> 'properties' ->> 'days_eaten_only_one_meal_uf') as days_eaten_only_one_meal,
    COALESCE(data -> 'properties' ->> 'days_or_activities_missed_lack_hygiene_products_sr', data -> 'properties' ->> 'days_or_activities_missed_lack_hygiene_products_uf') as days_or_activities_missed_lack_hygiene_products,
    data -> 'properties' ->> 'delivering_apprenticeshiptrainings_before_apbl' as delivering_apprenticeshiptrainings_before_apbl,
    data -> 'properties' ->> 'did_participant_own_business_before_pl' as did_participant_own_business_before_pl,
    data -> 'properties' ->> 'digital_literacy-center-dl' as digital_literacy_center_dl,
    data -> 'properties' ->> 'digital_literacy_dl' as digital_literacy_dl,
    data -> 'properties' ->> 'dignity_kit_package_dka' as dignity_kit_package_dka,
    data -> 'properties' ->> 'dignity_kit_support' as dignity_kit_support,
    data -> 'properties' ->> 'dignity_package_helpful_dka' as dignity_package_helpful_dka,
    data -> 'properties' ->> 'dignity_received_dki' as dignity_received_dki,
    data -> 'properties' ->> 'disability_type_csf' as disability_type_csf,
    data -> 'properties' ->> 'document_provided_apbl' as document_provided_apbl,
    COALESCE(data -> 'properties' ->> 'documents_pl', data -> 'properties' ->> 'documents_sr') as documents,
    data -> 'properties' ->> 'does_business_have_capacity_for_growth_bga' as does_business_have_capacity_for_growth_bga,
    data -> 'properties' ->> 'does_business_have_employees' as does_business_have_employees,
    data -> 'properties' ->> 'do_you_have_any_disability_apbl' as do_you_have_any_disability_apbl,
    COALESCE(data -> 'properties' ->> 'do_you_have_children_sr', data -> 'properties' ->> 'do_you_have_children_uf') as do_you_have_children,
    data -> 'properties' ->> 'do_you_have_employees_apbl' as do_you_have_employees_apbl,
    data -> 'properties' ->> 'do_you_recommend_beneficiary_to_proceed_uf' as do_you_recommend_beneficiary_to_proceed_uf,
    data -> 'properties' ->> 'do_you_recommended_institute_ttia' as do_you_recommended_institute_ttia,
    data -> 'properties' ->> 'dropped_courses' as dropped_courses,
    data -> 'properties' ->> 'duration_as_sun_member_apbl' as duration_as_sun_member_apbl,
    data -> 'properties' ->> 'duration_dka' as duration_dka,
    data -> 'properties' ->> 'duration_of_course_ttia' as duration_of_course_ttia,
    data -> 'properties' ->> 'duration_on_the_activity_dki' as duration_on_the_activity_dki,
    data -> 'properties' ->> 'duration_upskilling_program_uf' as duration_upskilling_program_uf,
    data -> 'properties' ->> 'educational_certificates_uf' as educational_certificates_uf,
    data -> 'properties' ->> 'elaborate_bm' as elaborate_bm,
    data -> 'properties' ->> 'eligible_for_daycaresupport_dc' as eligible_for_daycaresupport_dc,
    data -> 'properties' ->> 'employees_bm' as employees_bm,
    data -> 'properties' ->> 'employees_pl' as employees_pl,
    data -> 'properties' ->> 'employees_sr' as employees_sr,
    data -> 'properties' ->> 'employment_specific_role_sr' as employment_specific_role_sr,
    data -> 'properties' ->> 'employment_type_sr' as employment_type_sr,
    data -> 'properties' ->> 'end_date_sr' as end_date_sr,
    data -> 'properties' ->> 'engaging_in_social_and_public_impacts_ttia' as engaging_in_social_and_public_impacts_ttia,
    data -> 'properties' ->> 'enrolled_tvet_course_tvbl' as enrolled_tvet_course_tvbl,
    data -> 'properties' ->> 'enumerator' as enumerator,
    COALESCE(data -> 'properties' ->> 'Enumerator_First_Name', data -> 'properties' ->> 'enumerators_first') as enumerator_first_Name,
    COALESCE(data -> 'properties' ->> 'enumerator_last-name', data -> 'properties' ->> 'Enumerator_Second_Name') as enumerator_last_name,
    data -> 'properties' ->> 'ever_enrolled_high_cost' as ever_enrolled_high_cost,
    data -> 'properties' ->> 'existing_management_board_ttia' as existing_management_board_ttia,
    data -> 'properties' ->> 'expected_completion_date_tvbl' as expected_completion_date_tvbl,
    data -> 'properties' ->> 'expected_completion_date-uf' as expected_completion_date_uf,
    data -> 'properties' ->> 'expected_end_date_of_training_st' as expected_end_date_of_training_st,
    data -> 'properties' ->> 'experienced_days_where_you_had_nothing_sr' as experienced_days_where_you_had_nothing_sr,
    data -> 'properties' ->> 'experienced_days_where_you_had_nothing_uf' as experienced_days_where_you_had_nothing_uf,
    data -> 'properties' ->> 'explain_why_tc' as explain_why_tc,
    data -> 'properties' ->> 'fees_per_training_apbl' as fees_per_training_apbl,
    data -> 'properties' ->> 'female_employees_bm' as female_employees_bm,
    data -> 'properties' ->> 'female_employees_pl' as female_employees_pl,
    data -> 'properties' ->> 'final_business_recomendation_to_mentee_bm' as final_business_recomendation_to_mentee_bm,
    data -> 'properties' ->> 'final_exams_tc' as final_exams_tc,
    data -> 'properties' ->> 'first_visit_done' as first_visit_done,
    data -> 'properties' ->> 'Forego_basic_essentials_dka' as Forego_basic_essentials_dka,
    data -> 'properties' ->> 'forego_basic_essentials_sr' as forego_basic_essentials_sr,
    data -> 'properties' ->> 'forego_basic_essentials_uf' as forego_basic_essentials_uf,
    data -> 'properties' ->> 'formal_education_dir' as formal_education_dir,

    data -> 'properties' ->> 'gender_of_the_apprentice_provider_apbl' as gender_of_the_apprentice_provider_apbl,
    data -> 'properties' ->> 'gender_of_the_beneficiary_dki' as gender_of_the_beneficiary_dki,
    data -> 'properties' ->> 'gps_of_business_location_apbl' as gps_of_business_location_apbl,
    data -> 'properties' ->> 'grant_amount_bg' as grant_amount_bg,
    data -> 'properties' ->> 'grant_month' as grant_month,
    data -> 'properties' ->> 'grant_source_bg' as grant_source_bg,
    data -> 'properties' ->> 'group_psr' as group_psr,
    data -> 'properties' ->> 'guardian_alternative_phone_number_tvet' as guardian_alternative_phone_number_tvet,
    data -> 'properties' ->> 'guardian_alternative_phone_tvbl' as guardian_alternative_phone_tvbl,
    data -> 'properties' ->> 'guardian_name_tvbl' as guardian_name_tvbl,
    data -> 'properties' ->> 'guardian_phone_number_tvbl' as guardian_phone_number_tvbl,
    data -> 'properties' ->> 'guardians_alternative_number_apr' as guardians_alternative_number_apr,
    data -> 'properties' ->> 'guardians_name_apr' as guardians_name_apr,
    data -> 'properties' ->> 'guardians_phone_number_apr' as guardians_phone_number_apr,
    data -> 'properties' ->> 'handcraft_training_type_hc' as handcraft_training_type_hc,
    data -> 'properties' ->> 'handcraft_training_type_sr' as handcraft_training_type_sr,
    data -> 'properties' ->> 'has_taken_high_cost' as has_taken_high_cost,
    data -> 'properties' ->> 'have_alumni_network_ttia' as have_alumni_network_ttia,
    data -> 'properties' ->> 'have_bank_account_apbl' as have_bank_account_apbl,
    data -> 'properties' ->> 'have_children_with_disabilities_sr' as have_children_with_disabilities_sr,
    data -> 'properties' ->> 'have_trainers_apbl' as have_trainers_apbl,
    data -> 'properties' ->> 'head_gender_sr' as head_gender_sr,
    data -> 'properties' ->> 'head_gender_uf' as head_gender_uf,
    data -> 'properties' ->> 'Head_hh_dka' as Head_hh_dka,
    data -> 'properties' ->> 'hearing_impairment_dir' as hearing_impairment_dir,
    data -> 'properties' ->> 'hearing_impairment_tvbl' as hearing_impairment_tvbl,
    data -> 'properties' ->> 'hh_engaged_in_work_sr' as hh_engaged_in_work_sr,
    data -> 'properties' ->> 'hh_engaged_in_work_uf' as hh_engaged_in_work_uf,
    COALESCE(data -> 'properties' ->> 'household_head_sr', data -> 'properties' ->> 'household_head_uf') as household_head,
    data -> 'properties' ->> 'how_doy_require_bga' as how_doy_require_bga,
    data -> 'properties' ->> 'how_helpful_course' as how_helpful_course,
    data -> 'properties' ->> 'how_helpful_course_tc' as how_helpful_course_tc,
    data -> 'properties' ->> 'how_helpful_was_upskilling_uc' as how_helpful_was_upskilling_uc,
    data -> 'properties' ->> 'how_long_business_been_in_operation_bga' as how_long_business_been_in_operation_bga,
    data -> 'properties' ->> 'how_many_branches_apbl' as how_many_branches_apbl,
    COALESCE(data -> 'properties' ->> 'how_many_children_dc', data -> 'properties' ->> 'how_many_children_sr', data -> 'properties' ->> 'how_many_children_uf') as how_many_children,
    data -> 'properties' ->> 'how_many_children_inneed_of_daycare_dc' as how_many_children_inneed_of_daycare_dc,
    data -> 'properties' ->> 'how_many_csf' as how_many_csf,
    data -> 'properties' ->> 'how_many_employed_female_apbl' as how_many_employed_female_apbl,
    data -> 'properties' ->> 'how_many_employed_male_apbl' as how_many_employed_male_apbl,
    data -> 'properties' ->> 'how_many_employees_bga' as how_many_employees_bga,
    data -> 'properties' ->> 'how_many_employees_bm' as how_many_employees_bm,
    data -> 'properties' ->> 'how_many_females_bga' as how_many_females_bga,
    data -> 'properties' ->> 'how_many_nita_courses_offered_ttia' as how_many_nita_courses_offered_ttia,
    data -> 'properties' ->> 'how_many_trainers_apbl' as how_many_trainers_apbl,
    data -> 'properties' ->> 'how_many_youth_mermbers_bga' as how_many_youth_mermbers_bga,
    data -> 'properties' ->> 'how_much_money_required_to_implement_bga' as how_much_money_required_to_implement_bga,
    data -> 'properties' ->> 'how_often_mentee_buys_stock_bm' as how_often_mentee_buys_stock_bm,
    data -> 'properties' ->> 'how_to_assess_apbl' as how_to_assess_apbl,
    data -> 'properties' ->> 'how_to_mitigate_challenges_bga' as how_to_mitigate_challenges_bga,
    data -> 'properties' ->> 'id_non_citizen_dir' as id_non_citizen_dir,
    data -> 'properties' ->> 'id_number_csf' as id_number_csf,
    data -> 'properties' ->> 'if_issued_with_dignity_kit_dka' as if_issued_with_dignity_kit_dka,
    data -> 'properties' ->> 'if_mentee_always_have_the_cash_to_buy_new_stock_bm' as if_mentee_always_have_the_cash_to_buy_new_stock_bm,
    data -> 'properties' ->> 'if_mentee_have_dead_stock_bm' as if_mentee_have_dead_stock_bm,
    data -> 'properties' ->> 'If_no_capacity_bga' as If_no_capacity_bga,
    data -> 'properties' ->> 'if_no_explain_why' as if_no_explain_why,
    data -> 'properties' ->> 'if_no_how_apbl' as if_no_how_apbl,
    data -> 'properties' ->> 'if_no_indicate_the_reasons_ttia' as if_no_indicate_the_reasons_ttia,
    data -> 'properties' ->> 'if_no_joinining_schedule_apbl' as if_no_joinining_schedule_apbl,
    data -> 'properties' ->> 'if_no_profit_bga' as if_no_profit_bga,
    data -> 'properties' ->> 'if_not_satisfied_ask_why_tvbl' as if_not_satisfied_ask_why_tvbl,
    data -> 'properties' ->> 'if_not_sure_bga' as if_not_sure_bga,
    data -> 'properties' ->> 'if_no_why_bga' as if_no_why_bga,
    data -> 'properties' ->> 'if_no_why_tc' as if_no_why_tc,
    data -> 'properties' ->> 'if_no_why_tvbl' as if_no_why_tvbl,
    data -> 'properties' ->> 'if_other_please_specify_apbl' as if_other_please_specify_apbl,
    data -> 'properties' ->> 'if_other_please_state_tvbl' as if_other_please_state_tvbl,
    data -> 'properties' ->> 'if_other_purpose_bga' as if_other_purpose_bga,
    data -> 'properties' ->> 'if_others_specify_tvbl' as if_others_specify_tvbl,
    data -> 'properties' ->> 'if_referred_by_shofco_staff_and_related_apbl' as if_referred_by_shofco_staff_and_related_apbl,
    data -> 'properties' ->> 'if_yes_explain_tvbl' as if_yes_explain_tvbl,
    data -> 'properties' ->> 'if_yes_for_how_long_apbl' as if_yes_for_how_long_apbl,
    data -> 'properties' ->> 'if_yes_please_state_apbl' as if_yes_please_state_apbl,
    data -> 'properties' ->> 'if_yes_specify_disability_type_apbl' as if_yes_specify_disability_type_apbl,
    data -> 'properties' ->> 'if_yes_what_types_of_work_dc' as if_yes_what_types_of_work_dc,
    data -> 'properties' ->> 'inclusive_fees_ttia' as inclusive_fees_ttia,
    data -> 'properties' ->> 'income_on_average_pl' as income_on_average_pl,
    data -> 'properties' ->> 'income_on_average_placement' as income_on_average_placement,
    data -> 'properties' ->> 'indicate_courses_recommended_ttia' as indicate_courses_recommended_ttia,
    data -> 'properties' ->> 'indicate_recommendation_reasons_ttia' as indicate_recommendation_reasons_ttia,
    data -> 'properties' ->> 'institute_location_accessible_ttia' as institute_location_accessible_ttia,
    data -> 'properties' ->> 'institute_ttia' as institute_ttia,
    data -> 'properties' ->> 'institution_name_dc' as institution_name_dc,
    data -> 'properties' ->> 'interest_in_sales_work_ent' as interest_in_sales_work_ent,
    data -> 'properties' ->> 'interest_in_sales_work_if_opportunity_arises_sr' as interest_in_sales_work_if_opportunity_arises_sr,
    data -> 'properties' ->> 'interest_in_sales_work_iga' as interest_in_sales_work_iga,
    data -> 'properties' ->> 'interest_in_sales_work_sr' as interest_in_sales_work_sr,
    data -> 'properties' ->> 'internal_exam_tc' as internal_exam_tc,
    data -> 'properties' ->> 'intern_name' as intern_name,
    data -> 'properties' ->> 'internship_position_int' as internship_position_int,
    data -> 'properties' ->> 'intervention_dka' as intervention_dka,
    data -> 'properties' ->> 'intervention_the_beneficiary_is_under_dki' as intervention_the_beneficiary_is_under_dki,
    data -> 'properties' ->> 'interviewer_name_tvbl' as interviewer_name_tvbl,
    data -> 'properties' ->> 'is_business_registered_with_govt_bga' as is_business_registered_with_govt_bga,
    data -> 'properties' ->> 'is_completed' as is_completed,
    data -> 'properties' ->> 'is_course_marketable_ttia' as is_course_marketable_ttia,
    data -> 'properties' ->> 'is_existing_participant' as is_existing_participant,
    data -> 'properties' ->> 'is_group_govt_registered_bga' as is_group_govt_registered_bga,
    data -> 'properties' ->> 'is_group_registered_with_sun_bga' as is_group_registered_with_sun_bga,
    data -> 'properties' ->> 'is_this_participant_a_person_living_with_disability_dir' as is_this_participant_a_person_living_with_disability_dir,
    data -> 'properties' ->> 'job_placement_support_needed_sr' as job_placement_support_needed_sr,
    data -> 'properties' ->> 'job_position_pl' as job_position_pl,
    data -> 'properties' ->> 'job_transition_pl' as job_transition_pl,
    data -> 'properties' ->> 'kcse_grade_dir' as kcse_grade_dir,
    data -> 'properties' ->> 'kcse_grade_dl' as kcse_grade_dl,
    data -> 'properties' ->> 'kcse_grade_of_participant_sr' as kcse_grade_of_participant_sr,
    data -> 'properties' ->> 'kcse_grade_sr' as kcse_grade_sr,
    data -> 'properties' ->> 'kcse_grade_uf' as kcse_grade_uf,
    data -> 'properties' ->> 'kenyan_national_id_card_dir' as kenyan_national_id_card_dir,
    data -> 'properties' ->> 'kenyan_national_id_number_dir' as kenyan_national_id_number_dir,
    data -> 'properties' ->> 'key_challenges_that_might_affect_the_business_bga' as key_challenges_that_might_affect_the_business_bga,
    data -> 'properties' ->> 'kind_of_work_or_activity_tvbl' as kind_of_work_or_activity_tvbl,
    data -> 'properties' ->> 'last_name__surname_dir' as last_name__surname_dir,
    data -> 'properties' ->> 'learning_disorders_dir' as learning_disorders_dir,
    data -> 'properties' ->> 'learning_materials_to_access_apbl' as learning_materials_to_access_apbl,
    data -> 'properties' ->> 'lenght_of_training_program_apbl' as lenght_of_training_program_apbl,
    data -> 'properties' ->> 'level_of_education_dir' as level_of_education_dir,
    data -> 'properties' ->> 'level_of_satisfaction_with_training_tvbl' as level_of_satisfaction_with_training_tvbl,
    data -> 'properties' ->> 'list_available_resources_apbl' as list_available_resources_apbl,
    data -> 'properties' ->> 'location_dka' as location_dka,
    data -> 'properties' ->> 'location_of_institute_ttia' as location_of_institute_ttia,
    data -> 'properties' ->> 'main_source_of_energy_for_cooking' as main_source_of_energy_for_cooking,
    data -> 'properties' ->> 'marital_status_dc' as marital_status_dc,
    data -> 'properties' ->> 'marital_status_dki' as marital_status_dki,
    data -> 'properties' ->> 'mark_the_location_of_the_business' as mark_the_location_of_the_business,
    data -> 'properties' ->> 'meeting_county_psr' as meeting_county_psr,
    data -> 'properties' ->> 'meeting_date_psr' as meeting_date_psr,
    data -> 'properties' ->> 'meeting_subcounty_psr' as meeting_subcounty_psr,
    data -> 'properties' ->> 'meeting_topic_psr' as meeting_topic_psr,
    data -> 'properties' ->> 'meeting_ward_psr' as meeting_ward_psr,
    data -> 'properties' ->> 'member_of_shofco_sacco_apbl' as member_of_shofco_sacco_apbl,
    data -> 'properties' ->> 'members_hh_dka' as members_hh_dka,
    data -> 'properties' ->> 'mental_disabilities_dir' as mental_disabilities_dir,
    data -> 'properties' ->> 'mental_disabilities_tvbl' as mental_disabilities_tvbl,
    data -> 'properties' ->> 'mentee_business_records_bm' as mentee_business_records_bm,
    data -> 'properties' ->> 'mentees_price_compared_to_competitors_bm' as mentees_price_compared_to_competitors_bm,
    data -> 'properties' ->> 'mentorship_county_bm' as mentorship_county_bm,
    data -> 'properties' ->> 'mentorship_subcounty_bm' as mentorship_subcounty_bm,
    data -> 'properties' ->> 'mentorship_ward_bm' as mentorship_ward_bm,
    data -> 'properties' ->> 'middle_name_dir' as middle_name_dir,
    data -> 'properties' ->> 'miss_school_due_to_lack_hygiene_products_sr' as miss_school_due_to_lack_hygiene_products_sr,
    data -> 'properties' ->> 'miss_school_due_to_lack_hygiene_products_uf' as miss_school_due_to_lack_hygiene_products_uf,
    data -> 'properties' ->> 'mode_of_learning_offered_ttia' as mode_of_learning_offered_ttia,
    data -> 'properties' ->> 'mode_of_training_dc' as mode_of_training_dc,
    data -> 'properties' ->> 'monitoring_student_performance_ttia' as monitoring_student_performance_ttia,
    data -> 'properties' ->> 'monthly_business_income_sr' as monthly_business_income_sr,
    data -> 'properties' ->> 'month_you_joined_dc' as month_you_joined_dc,
    data -> 'properties' ->> 'more_mentorship_sessions_bm' as more_mentorship_sessions_bm,
    data -> 'properties' ->> 'mpesa_first_name_bg' as mpesa_first_name_bg,
    data -> 'properties' ->> 'mpesa_number_bg' as mpesa_number_bg,
    data -> 'properties' ->> 'mpesa_number_sp' as mpesa_number_sp,
    data -> 'properties' ->> 'mpesa_second_name_bg' as mpesa_second_name_bg,
    data -> 'properties' ->> 'name_of_assessor_1_ttia' as name_of_assessor_1_ttia,
    data -> 'properties' ->> 'name_of_assessor_2_ttia' as name_of_assessor_2_ttia,
    data -> 'properties' ->> 'name_of_assessor_3_ttia' as name_of_assessor_3_ttia,
    data -> 'properties' ->> 'name_of_course_ttia' as name_of_course_ttia,
    data -> 'properties' ->> 'name_of_deputy_manager_ttia' as name_of_deputy_manager_ttia,
    data -> 'properties' ->> 'name_of_facilitator' as name_of_facilitator,
    data -> 'properties' ->> 'name_of_institution_ttia' as name_of_institution_ttia,
    data -> 'properties' ->> 'name_of_institution_tvet' as name_of_institution_tvet,
    data -> 'properties' ->> 'name_of_mentor_bm' as name_of_mentor_bm,
    data -> 'properties' ->> 'name_of_officer_dir' as name_of_officer_dir,
    data -> 'properties' ->> 'name_of_organization_int' as name_of_organization_int,
    data -> 'properties' ->> 'name_of_organization_pl' as name_of_organization_pl,
    data -> 'properties' ->> 'name_of_org_dka' as name_of_org_dka,
    data -> 'properties' ->> 'name_of_sl_staff_dki' as name_of_sl_staff_dki,
    data -> 'properties' ->> 'name_of_sl_staff_sr' as name_of_sl_staff_sr,
    data -> 'properties' ->> 'name_of_the_assessor' as name_of_the_assessor,
    data -> 'properties' ->> 'name_of_the_assessor_apbl' as name_of_the_assessor_apbl,
    data -> 'properties' ->> 'name_of_the_beneficiary_dki' as name_of_the_beneficiary_dki,
    data -> 'properties' ->> 'name_of_the_business_apbl' as name_of_the_business_apbl,
    data -> 'properties' ->> 'name_of_the_group_bga' as name_of_the_group_bga,
    data -> 'properties' ->> 'name_of_the_mentee_bm' as name_of_the_mentee_bm,
    data -> 'properties' ->> 'name_of_the_mentor_bm' as name_of_the_mentor_bm,
    data -> 'properties' ->> 'name_of_tvet_institute_dki' as name_of_tvet_institute_dki,
    data -> 'properties' ->> 'name_sl_staff_placement' as name_sl_staff_placement,
    data -> 'properties' ->> 'natiional_id_card_dir' as natiional_id_card_dir,
    data -> 'properties' ->> 'national_id_no_bm' as national_id_no_bm,
    data -> 'properties' ->> 'national_id_number_dir' as national_id_number_dir,
    data -> 'properties' ->> 'national_id_or_proof_of_registration_number_dki' as national_id_or_proof_of_registration_number_dki,
    data -> 'properties' ->> 'nationality_of_the_beneficiary_dki' as nationality_of_the_beneficiary_dki,
    data -> 'properties' ->> 'nationality_of_the_mentee_bm' as nationality_of_the_mentee_bm,
    data -> 'properties' ->> 'nature_of_emplyment_pl' as nature_of_emplyment_pl,
    data -> 'properties' ->> 'nature_of_selfemplyment_pl' as nature_of_selfemplyment_pl,
    data -> 'properties' ->> 'nature_of_transition_pl' as nature_of_transition_pl,
    data -> 'properties' ->> 'nature_of_transition_placement' as nature_of_transition_placement,
    data -> 'properties' ->> 'Nature_of_your_business_bga' as Nature_of_your_business_bga,
    data -> 'properties' ->> 'need_for_training_sr' as need_for_training_sr,
    data -> 'properties' ->> 'neuro-developmental_disabilities_dir' as neuro_developmental_disabilities_dir,
    data -> 'properties' ->> 'new_role_pl' as new_role_pl,
    data -> 'properties' ->> 'new_role_through_individual_support_pl' as new_role_through_individual_support_pl,
    data -> 'properties' ->> 'new_role_through_shofco_support_pl' as new_role_through_shofco_support_pl,
    data -> 'properties' ->> 'nita_exams' as nita_exams,
    data -> 'properties' ->> 'nita_exams_tc' as nita_exams_tc,
    data -> 'properties' ->> 'no_nita_exams_tc' as no_nita_exams_tc,
    data -> 'properties' ->> 'non-shofco_training_pl' as non_shofco_training_pl,
    data -> 'properties' ->> 'no_of_meals_reduced_dka' as no_of_meals_reduced_dka,
    data -> 'properties' ->> 'no_provide_details_bga' as no_provide_details_bga,
    data -> 'properties' ->> 'no_source_of_income_how_coping_tvbl' as no_source_of_income_how_coping_tvbl,
    COALESCE(data -> 'properties' ->> 'number_of_children_sr', data -> 'properties' ->> 'number_of_children-uf') as number_of_children,
    COALESCE(data -> 'properties' ->> 'number_of_days_without_hygiene_items_sr', data -> 'properties' ->> 'number_of_days_without_hygiene_items_uf') as number_of_days_without_hygiene_items,
    data -> 'properties' ->> 'number_of_employees_in_business_sr' as number_of_employees_in_business_sr,
    data -> 'properties' ->> 'number_of_employees_pl' as number_of_employees_pl,
    data -> 'properties' ->> 'number_of_employees_sr' as number_of_employees_sr,
    data -> 'properties' ->> 'number_of_female_employees_sr' as number_of_female_employees_sr,
    data -> 'properties' ->> 'number_of_meals_reduced_sr' as number_of_meals_reduced_sr,
    data -> 'properties' ->> 'number_of_meals_reduced_uf' as number_of_meals_reduced_uf,
    data -> 'properties' ->> 'number_of_teachers_ttia' as number_of_teachers_ttia,
    data -> 'properties' ->> 'offering_internal_certification_ttia' as offering_internal_certification_ttia,
    data -> 'properties' ->> 'offering_knec_exams_ttia' as offering_knec_exams_ttia,
    data -> 'properties' ->> 'offering_nita_exams_ttia' as offering_nita_exams_ttia,
    data -> 'properties' ->> 'officer_name_dir' as officer_name_dir,
    data -> 'properties' ->> 'officer_name_psr' as officer_name_psr,
    data -> 'properties' ->> 'official_contact_of_the_apprentice_provider_apbl' as official_contact_of_the_apprentice_provider_apbl,
    data -> 'properties' ->> 'official_name_of_the_apprentice_provider_apbl' as official_name_of_the_apprentice_provider_apbl,
    data -> 'properties' ->> 'on_average_how_much_raised_bga' as on_average_how_much_raised_bga,
    data -> 'properties' ->> 'ongoing_course' as ongoing_course,
    data -> 'properties' ->> 'on_rate_does_applicantgroup_have_experience_bga' as on_rate_does_applicantgroup_have_experience_bga,
    data -> 'properties' ->> 'on_rate_is_business_idea_viable_bga' as on_rate_is_business_idea_viable_bga,
    data -> 'properties' ->> 'on_rate_ismarket_identified_realistic_bga' as on_rate_ismarket_identified_realistic_bga,
    data -> 'properties' ->> 'organization_sector_pl' as organization_sector_pl,
    data -> 'properties' ->> 'organization_sponsoring_student_tvet' as organization_sponsoring_student_tvet,
    data -> 'properties' ->> 'other_additional_values_ttia' as other_additional_values_ttia,
    data -> 'properties' ->> 'other_benefit_offered_tvbl' as other_benefit_offered_tvbl,
    data -> 'properties' ->> 'other_bg' as other_bg,
    data -> 'properties' ->> 'other_course_tvet' as other_course_tvet,
    data -> 'properties' ->> 'other_group_psr' as other_group_psr,
    data -> 'properties' ->> 'other_handcraft_hc' as other_handcraft_hc,
    data -> 'properties' ->> 'other_iga' as other_iga,
    data -> 'properties' ->> 'other_interests__tvbl' as other_interests__tvbl,
    data -> 'properties' ->> 'other_kcse_grade_uf' as other_kcse_grade_uf,
    data -> 'properties' ->> 'other_legal_documents_apbl' as other_legal_documents_apbl,
    data -> 'properties' ->> 'other_program_pl' as other_program_pl,
    data -> 'properties' ->> 'other_program_sr' as other_program_sr,
    data -> 'properties' ->> 'other_reason_csr' as other_reason_csr,
    data -> 'properties' ->> 'other_safeguarding_measures_specify_ttia' as other_safeguarding_measures_specify_ttia,
    data -> 'properties' ->> 'other_sector_int' as other_sector_int,
    data -> 'properties' ->> 'other_sector-pl' as other_sector_pl,
    data -> 'properties' ->> 'other_service_the_participant_is_interested_in_dir' as other_service_the_participant_is_interested_in_dir,
    data -> 'properties' ->> 'other_skill_apr' as other_skill_apr,
    data -> 'properties' ->> 'other_social_platforms_ttia' as other_social_platforms_ttia,
    data -> 'properties' ->> 'other_stock_bm' as other_stock_bm,
    data -> 'properties' ->> 'other_support_dka' as other_support_dka,
    data -> 'properties' ->> 'other_support_to_ensure_transition_ttia' as other_support_to_ensure_transition_ttia,
    data -> 'properties' ->> 'other_training_center_uf' as other_training_center_uf,
    data -> 'properties' ->> 'other_training_program_uf' as other_training_program_uf,
    data -> 'properties' ->> 'other_training_specify_bga' as other_training_specify_bga,
    data -> 'properties' ->> 'other_tvet_course_tvbl' as other_tvet_course_tvbl,
    data -> 'properties' ->> 'other_value_adittion_to_students_ttia' as other_value_adittion_to_students_ttia,
    data -> 'properties' ->> 'other_year_bga' as other_year_bga,
    data -> 'properties' ->> 'output_of_the_agreed_implemented_activities_bm' as output_of_the_agreed_implemented_activities_bm,
    data -> 'properties' ->> 'overview_of_shop_apbl' as overview_of_shop_apbl,
    data -> 'properties' ->> 'owner_id' as owner_id,
    data -> 'properties' ->> 'parent_dka' as parent_dka,
    data -> 'properties' ->> 'parent_name_tvet' as parent_name_tvet,
    data -> 'properties' ->> 'parent_phone_number_tvet' as parent_phone_number_tvet,
    data -> 'properties' ->> 'parent_tvbl' as parent_tvbl,
    data -> 'properties' ->> 'Partnerships_Grant' as Partnerships_Grant,
    data -> 'properties' ->> 'payroll_calculation' as payroll_calculation,
    data -> 'properties' ->> 'people_attending_psr' as people_attending_psr,
    data -> 'properties' ->> 'phone_number_with_plus' as phone_number_with_plus,
    data -> 'properties' ->> 'physical_disabilities_dir' as physical_disabilities_dir,
    data -> 'properties' ->> 'physical_disabilities_tvbl' as physical_disabilities_tvbl,
    data -> 'properties' ->> 'pieces_produced_sp' as pieces_produced_sp,
    data -> 'properties' ->> 'placement_date_apr' as placement_date_apr,
    data -> 'properties' ->> 'placement_opportunity_pl' as placement_opportunity_pl,
    data -> 'properties' ->> 'placement_within_shofco_int' as placement_within_shofco_int,
    data -> 'properties' ->> 'please_explain_why_tc' as please_explain_why_tc,
    data -> 'properties' ->> 'please_specify_social_and_public_impacts_ttia' as please_specify_social_and_public_impacts_ttia,
    data -> 'properties' ->> 'post-graduation_plans_tvbl' as post_graduation_plans_tvbl,
    data -> 'properties' ->> 'post_training_support_needed_sr' as post_training_support_needed_sr,
    data -> 'properties' ->> 'predominant_wall_material_tvbl' as predominant_wall_material_tvbl,
    data -> 'properties' ->> 'preferred_region_sr' as preferred_region_sr,
    data -> 'properties' ->> 'preferred_sectors_for_employment_sr' as preferred_sectors_for_employment_sr,
    data -> 'properties' ->> 'preferred_time_of_training_sr' as preferred_time_of_training_sr,
    data -> 'properties' ->> 'previously_enrolled_uf' as previously_enrolled_uf,
    data -> 'properties' ->> 'previous_service_completed' as previous_service_completed,
    data -> 'properties' ->> 'previous_training' as previous_training,
    COALESCE(data -> 'properties' ->> 'primary_phone_number_dir', data -> 'properties' ->> 'primary_phone_number_csf') as primary_phone_number,
    data -> 'properties' ->> 'prior_skilling_course_tvbl' as prior_skilling_course_tvbl,
    data -> 'properties' ->> 'product_made_sp' as product_made_sp,
    data -> 'properties' ->> 'profession_of_facilitator_psr' as profession_of_facilitator_psr,
    data -> 'properties' ->> 'program_donor_placement' as program_donor_placement,
    data -> 'properties' ->> 'program_psr' as program_psr,
    data -> 'properties' ->> 'program_the_participant_is_under_sr' as program_the_participant_is_under_sr,
    data -> 'properties' ->> 'progress_reviews_ofteness_apbl' as progress_reviews_ofteness_apbl,
    data -> 'properties' ->> 'psychosocial_facilitator_psr' as psychosocial_facilitator_psr,
    data -> 'properties' ->> 'Purpose_of_the_grant_bga' as purpose_of_the_grant_bga,
    data -> 'properties' ->> 'pwd_card_no_dir' as pwd_card_no_dir,
    data -> 'properties' ->> 'reason_close' as reason_close,
    COALESCE(data -> 'properties' ->> 'reason_not_completed', data -> 'properties' ->> 'reason_not_completed_tc') as reason_not_completed,
    data -> 'properties' ->> 'reason_not_upskilling_uf' as reason_not_upskilling_uf,
    data -> 'properties' ->> 'reasons_you_think_your_business_should_be_selected_bga' as reasons_you_think_your_business_should_be_selected_bga,
    data -> 'properties' ->> 'received_ongoing_recurring_support_dka' as received_ongoing_recurring_support_dka,
    COALESCE(data -> 'properties' ->> 'receiving_aid_sr', data -> 'properties' ->> 'receiving_aid_uf') as receiving_aid,
    data -> 'properties' ->> 'recommended_institute_for_partnership_ttia' as recommended_institute_for_partnership_ttia,
    COALESCE(data -> 'properties' ->> 'recommend_training', data -> 'properties' ->> 'recommend_training_tc') as recommend_training,
    data -> 'properties' ->> 'recording_ses' as recording_ses,
    data -> 'properties' ->> 'referral_dir' as referral_dir,
    data -> 'properties' ->> 'referred_by_dir' as referred_by_dir,
    data -> 'properties' ->> 'refugee_type_dir' as refugee_type_dir,
    COALESCE(data -> 'properties' ->> 'region', data -> 'properties' ->> 'region_bm', data -> 'properties' ->> 'region_int') as region,
    data -> 'properties' ->> 'region_located_apbl' as region_located_apbl,
    data -> 'properties' ->> 'region_of_business_transition_pl' as region_of_business_transition_pl,
    data -> 'properties' ->> 'region_of_business_transition_placement' as region_of_business_transition_placement,
    data -> 'properties' ->> 'region_of_the_mentorship_bm' as region_of_the_mentorship_bm,
    data -> 'properties' ->> 'regions_int' as regions_int,
    COALESCE(data -> 'properties' ->> 'registration_document_csf', data -> 'properties' ->> 'registration_document_dir') as registration_document,
    data -> 'properties' ->> 'registration_document_of_the_participant_dir' as registration_document_of_the_participant_dir,
    data -> 'properties' ->> 'regularly_monitoring_progres_apbl' as regularly_monitoring_progres_apbl,
    data -> 'properties' ->> 'resources_available_apbl' as resources_available_apbl,
    data -> 'properties' ->> 'resources_equipment_ttia' as resources_equipment_ttia,
    data -> 'properties' ->> 'revenue_sp' as revenue_sp,
    data -> 'properties' ->> 'safeguarding_measures_implemented_ttia' as safeguarding_measures_implemented_ttia,
    data -> 'properties' ->> 'safety_gears_availability_ttia' as safety_gears_availability_ttia,
    data -> 'properties' ->> 'school_official_contact_ttia' as school_official_contact_ttia,
    data -> 'properties' ->> 'sector_of_the_organization_int' as sector_of_the_organization_int,
    data -> 'properties' ->> 'service_completed' as service_completed,
    data -> 'properties' ->> 'service_of_interest_dir' as service_of_interest_dir,
    data -> 'properties' ->> 'service_the_participant_is_interested_in_dir' as service_the_participant_is_interested_in_dir,
    data -> 'properties' ->> 'session_of_training_sr' as session_of_training_sr,
    data -> 'properties' ->> 'shofco_partner_pl' as shofco_partner_pl,
    data -> 'properties' ->> 'shofco_program_int' as shofco_program_int,
    COALESCE(data -> 'properties' ->> 'shofco_site', data -> 'properties' ->> 'shofco_site_bm') as shofco_site,
    data -> 'properties' ->> 'shofco_sl-ds' as shofco_sl_ds,
    data -> 'properties' ->> 'shofco_training_participated_in_bga' as shofco_training_participated_in_bga,
    data -> 'properties' ->> 'skill_enrolled_apr' as skill_enrolled_apr,
    data -> 'properties' ->> 'skills_before_joining_shofco_sr' as skills_before_joining_shofco_sr,
    data -> 'properties' ->> 'skills_gained_pl' as skills_gained_pl,
    data -> 'properties' ->> 'skill_usefulness_in_job_tvbl' as skill_usefulness_in_job_tvbl,
    data -> 'properties' ->> 'sl_staff_sr' as sl_staff_sr,
    data -> 'properties' ->> 'social_platforms_active_ttia' as social_platforms_active_ttia,
    data -> 'properties' ->> 'solutions_agreed_to_be_implemented_bm' as solutions_agreed_to_be_implemented_bm,
    data -> 'properties' ->> 'source_of_income_dc' as source_of_income_dc,
    data -> 'properties' ->> 'specifically__kind_of_work_dc' as specifically__kind_of_work_dc,
    data -> 'properties' ->> 'specific_dignity_kit_package_received_dki' as specific_dignity_kit_package_received_dki,
    data -> 'properties' ->> 'specific_location_apbl' as specific_location_apbl,
    data -> 'properties' ->> 'specific_reason_for_accessing_csr' as specific_reason_for_accessing_csr,
    data -> 'properties' ->> 'specific_reason_for_accessing_space_csr' as specific_reason_for_accessing_space_csr,
    data -> 'properties' ->> 'specify_country_pl' as specify_country_pl,
    data -> 'properties' ->> 'specify_organization' as specify_organization,
    data -> 'properties' ->> 'specify_other_component' as specify_other_component,
    data -> 'properties' ->> 'specify_other_csr' as specify_other_csr,
    data -> 'properties' ->> 'specify_other_dl' as specify_other_dl,
    data -> 'properties' ->> 'specify_other_employment_sr' as specify_other_employment_sr,
    data -> 'properties' ->> 'specify_other_epz_center_uf' as specify_other_epz_center_uf,
    data -> 'properties' ->> 'specify_other_int' as specify_other_int,
    data -> 'properties' ->> 'specify_other_jobplacement_support_sr' as specify_other_jobplacement_support_sr,
    data -> 'properties' ->> 'specify_other_psr' as specify_other_psr,
    data -> 'properties' ->> 'specify_other_service_dir' as specify_other_service_dir,
    data -> 'properties' ->> 'specify_shofco_program_dir' as specify_shofco_program_dir,
    data -> 'properties' ->> 'specify_specialized_equipment_for_pwds_ttia' as specify_specialized_equipment_for_pwds_ttia,
    data -> 'properties' ->> 'specify_tc' as specify_tc,
    data -> 'properties' ->> 'specify_uf' as specify_uf,
    data -> 'properties' ->> 'speech_impairment_dir' as speech_impairment_dir,
    data -> 'properties' ->> 'speech_impairment_tvbl' as speech_impairment_tvbl,
    data -> 'properties' ->> 'staff_name_int' as staff_name_int,
    data -> 'properties' ->> 'staff_name_pl' as staff_name_pl,
    data -> 'properties' ->> 'staff_signature_sun_ttia' as staff_signature_sun_ttia,
    data -> 'properties' ->> 'staff_signature_ttia' as staff_signature_ttia,
    data -> 'properties' ->> 'start_date_dl' as start_date_dl,
    data -> 'properties' ->> 'start_date_ent' as start_date_ent,
    data -> 'properties' ->> 'start_date_hc' as start_date_hc,
    data -> 'properties' ->> 'start_date_iga' as start_date_iga,
    data -> 'properties' ->> 'start_date_int' as start_date_int,
    data -> 'properties' ->> 'start_date_of_training_st' as start_date_of_training_st,
    data -> 'properties' ->> 'start_date_of_upskilling-uf' as start_date_of_upskilling_uf,
    data -> 'properties' ->> 'start_date_sr' as start_date_sr,
    data -> 'properties' ->> 'start_date_tvbl' as start_date_tvbl,
    data -> 'properties' ->> 'start_date_tvet' as start_date_tvet,
    data -> 'properties' ->> 'state_the_reasons_dc' as state_the_reasons_dc,
    data -> 'properties' ->> 'state_your_nationality_apbl' as state_your_nationality_apbl,
    data -> 'properties' ->> 'status_of_education_dir' as status_of_education_dir,
    data -> 'properties' ->> 'status_of_level_of_education_dir' as status_of_level_of_education_dir,
    data -> 'properties' ->> 'stock_bm' as stock_bm,
    data -> 'properties' ->> 'stock_sr' as stock_sr,
    data -> 'properties' ->> 'student_capacity_ttia' as student_capacity_ttia,
    data -> 'properties' ->> 'student_shofco_sponsored_tvet' as student_shofco_sponsored_tvet,
    data -> 'properties' ->> 'subcounty_apprenticeship_provider_apr' as subcounty_apprenticeship_provider_apr,
    data -> 'properties' ->> 'subcounty_bm' as subcounty_bm,
    data -> 'properties' ->> 'subcounty_business_bga' as subcounty_business_bga,
    data -> 'properties' ->> 'subcounty_business_located_bga' as subcounty_business_located_bga,
    data -> 'properties' ->> 'subcounty_coworking_site_csf' as subcounty_coworking_site_csf,
    data -> 'properties' ->> 'sub_county_of_institution_ttia' as sub_county_of_institution_ttia,
    data -> 'properties' ->> 'sub-county_of_shofco_site_dir' as sub_county_of_shofco_site_dir,
    data -> 'properties' ->> 'subcounty_shofco_site_dir' as subcounty_shofco_site_dir,
    data -> 'properties' ->> 'successful_completion_other_stage_apbl' as successful_completion_other_stage_apbl,
    data -> 'properties' ->> 'sun_group_name_apbl' as sun_group_name_apbl,
    data -> 'properties' ->> 'sun_member_apbl' as sun_member_apbl,
    data -> 'properties' ->> 'Supervisor_phone_number_int' as Supervisor_phone_number_int,
    data -> 'properties' ->> 'supervisors_name_int' as supervisors_name_int,
    data -> 'properties' ->> 'support_given_to_ensure_transition_ttia' as support_given_to_ensure_transition_ttia,
    data -> 'properties' ->> 'support_through_individual_support_pl' as support_through_individual_support_pl,
    data -> 'properties' ->> 'support_to_help_succeed_as_entrepreneur_sr' as support_to_help_succeed_as_entrepreneur_sr,
    data -> 'properties' ->> 'swep_center_uf' as swep_center_uf,
    data -> 'properties' ->> 'swep_handcraft_center-hc' as swep_handcraft_center_hc,
    data -> 'properties' ->> 'swep-iga-center-iga' as swep_iga_center_iga,
    data -> 'properties' ->> 'swep_production_sp' as swep_production_sp,
    data -> 'properties' ->> 'swep_tailoring_center_st' as swep_tailoring_center_st,
    data -> 'properties' ->> 'telephone_number_of_the_beneficiary_dki' as telephone_number_of_the_beneficiary_dki,
    data -> 'properties' ->> 'time_attending_training_tvbl' as time_attending_training_tvbl,
    data -> 'properties' ->> 'time_in_csf' as time_in_csf,
    data -> 'properties' ->> 'time_in_csr' as time_in_csr,
    data -> 'properties' ->> 'time_of_training_dl' as time_of_training_dl,
    data -> 'properties' ->> 'time_of_training_sr' as time_of_training_sr,
    data -> 'properties' ->> 'time_out_csf' as time_out_csf,
    data -> 'properties' ->> 'time_out_csr' as time_out_csr,
    
    data -> 'properties' ->> 'trainees_that_can_be_accommodated_apbl' as trainees_that_can_be_accommodated_apbl,
    data -> 'properties' ->> 'training_activity' as training_activity,
    data -> 'properties' ->> 'training_activity_int' as training_activity_int,
    data -> 'properties' ->> 'training_activity_pl' as training_activity_pl,
    data -> 'properties' ->> 'training_activity_tc' as training_activity_tc,
    data -> 'properties' ->> 'training_activity_the_participant_was_undertaking_tc' as training_activity_the_participant_was_undertaking_tc,
    data -> 'properties' ->> 'training_activity_undertaken_placement' as training_activity_undertaken_placement,
    data -> 'properties' ->> 'training_center_uf' as training_center_uf,
    data -> 'properties' ->> 'training_course_the_participant_is_interested_in_dir' as training_course_the_participant_is_interested_in_dir,
    data -> 'properties' ->> 'training_delivery_apbl' as training_delivery_apbl,
    data -> 'properties' ->> 'training_program_uf' as training_program_uf,
    data -> 'properties' ->> 'training_session_sr' as training_session_sr,
    data -> 'properties' ->> 'training_session_st' as training_session_st,
    data -> 'properties' ->> 'training_type_iga' as training_type_iga,
    data -> 'properties' ->> 'transition_to_job_or_business_placement' as transition_to_job_or_business_placement,
    data -> 'properties' ->> 'trigger_sms_alert' as trigger_sms_alert,
    data -> 'properties' ->> 'tvet_accreditation_ttia' as tvet_accreditation_ttia,
    data -> 'properties' ->> 'tvet_county_placed_tvbl' as tvet_county_placed_tvbl,
    data -> 'properties' ->> 'tvet_institute_dka' as tvet_institute_dka,
    data -> 'properties' ->> 'tvet_institution_name_tvbl' as tvet_institution_name_tvbl,
    data -> 'properties' ->> 'tvet_institution_uf' as tvet_institution_uf,
    data -> 'properties' ->> 'type_of_business_apbl' as type_of_business_apbl,
    data -> 'properties' ->> 'type_of_business_bm' as type_of_business_bm,
    data -> 'properties' ->> 'type_of_business_owned_sr' as type_of_business_owned_sr,
    data -> 'properties' ->> 'type_of_business_pl' as type_of_business_pl,
    data -> 'properties' ->> 'type_of_business_sr' as type_of_business_sr,
    data -> 'properties' ->> 'type_of_business_you_operate_bga' as type_of_business_you_operate_bga,
    data -> 'properties' ->> 'type_of_disability' as type_of_disability,
    data -> 'properties' ->> 'type_of_disability_dir' as type_of_disability_dir,
    data -> 'properties' ->> 'type_of_disability_tvbl' as type_of_disability_tvbl,
    data -> 'properties' ->> 'type_of_exam_tc' as type_of_exam_tc,
    data -> 'properties' ->> 'type_of_institution_ttia' as type_of_institution_ttia,
    data -> 'properties' ->> 'types_of_work_engaged_in_tvbl' as types_of_work_engaged_in_tvbl,
    data -> 'properties' ->> 'unique_id' as unique_id,
    data -> 'properties' ->> 'unique_items_produced_sp' as unique_items_produced_sp,
    data -> 'properties' ->> 'unique_items_sold' as unique_items_sold,
    data -> 'properties' ->> 'unique_training' as unique_training,
    data -> 'properties' ->> 'unique_training_course_dir' as unique_training_course_dir,
    data -> 'properties' ->> 'unique_training_dir' as unique_training_dir,
    data -> 'properties' ->> 'unique_training_dr' as unique_training_dr,
    data -> 'properties' ->> 'unique_training_participant_interested_dir' as unique_training_participant_interested_dir,
    data -> 'properties' ->> 'updated_courses_list' as updated_courses_list,
    data -> 'properties' ->> 'user_location_id' as user_location_id,
    data -> 'properties' ->> 'using_coworking_for_a_living_csr' as using_coworking_for_a_living_csr,
    data -> 'properties' ->> 'using_coworking_to_earn_a_living_csf' as using_coworking_to_earn_a_living_csf,
    data -> 'properties' ->> 'Value_of_available_stock_bga' as Value_of_available_stock_bga,
    data -> 'properties' ->> 'visit_bm' as visit_bm,
    data -> 'properties' ->> 'visual_impairment_dir' as visual_impairment_dir,
    data -> 'properties' ->> 'visual_impairment_tvbl' as visual_impairment_tvbl,
    data -> 'properties' ->> 'waiting_card_serial_number' as waiting_card_serial_number,
    data -> 'properties' ->> 'ward_apprenticeship_provider_apr' as ward_apprenticeship_provider_apr,
    
    data -> 'properties' ->> 'was_the_particpant_referred_dir' as was_the_particpant_referred_dir,
    data -> 'properties' ->> 'wayforward_of_the_business_bm' as wayforward_of_the_business_bm,
    data -> 'properties' ->> 'were_you_referred_for_apprenticeship_apbl' as were_you_referred_for_apprenticeship_apbl,
    data -> 'properties' ->> 'what_is_your_tvet_training_completion_status' as what_is_your_tvet_training_completion_status,
    data -> 'properties' ->> 'what_kind_of_alumni_network_ttia' as what_kind_of_alumni_network_ttia,
    data -> 'properties' ->> 'what_visitor_is_using_csf' as what_visitor_is_using_csf,
    data -> 'properties' ->> 'what_visitor_is_using_csr' as what_visitor_is_using_csr,
    data -> 'properties' ->> 'Where_do_you_leave_your_children_dc' as Where_do_you_leave_your_children_dc,
    data -> 'properties' ->> 'whether_the_mentee_needs_more_mentorship_sessions_bm' as whether_the_mentee_needs_more_mentorship_sessions_bm,
    data -> 'properties' ->> 'which_complementary_courses_offered_ttia' as which_complementary_courses_offered_ttia,
    data -> 'properties' ->> 'which_exams__tvbl' as which_exams__tvbl,
    data -> 'properties' ->> 'which_swep_training_bga' as which_swep_training_bga,
    data -> 'properties' ->> 'who_referred_the_participant_dir' as who_referred_the_participant_dir,
    data -> 'properties' ->> 'who_referred_you_apbl' as who_referred_you_apbl,
    data -> 'properties' ->> 'Why_not_helpful_tc' as Why_not_helpful_tc,
    data -> 'properties' ->> 'why_not_helpful_uc' as why_not_helpful_uc,
    data -> 'properties' ->> 'why_participant_did_not_complete_their_training_tc' as why_participant_did_not_complete_their_training_tc,
    data -> 'properties' ->> 'willingness_to_relocate_sr' as willingness_to_relocate_sr,
    data -> 'properties' ->> 'willing_to_be_upskilled_uf' as willing_to_be_upskilled_uf,
    data -> 'properties' ->> 'willing_to_mentor_others_bga' as willing_to_mentor_others_bga,
    data -> 'properties' ->> 'willing_to_relocate_incase_of_available_job-opportunity_sr' as willing_to_relocate_incase_of_available_job_opportunity_sr,
    data -> 'properties' ->> 'willing_to_relocate_uf' as willing_to_relocate_uf,
    data -> 'properties' ->> 'willing_to_work_with_epz_uf' as willing_to_work_with_epz_uf,
    data -> 'properties' ->> 'work_areas_of_interest_sr' as work_areas_of_interest_sr,
    data -> 'properties' ->> 'work_participant_currently_engaged_in_sr' as work_participant_currently_engaged_in_sr,
    data -> 'properties' ->> 'written_business_plan_bga' as written_business_plan_bga,
    data -> 'properties' ->> 'year_attendend_training_bga' as year_attendend_training_bga,
    data -> 'properties' ->> 'year_business_operations_started_apbl' as year_business_operations_started_apbl,
    data -> 'properties' ->> 'year_business_started_pl' as year_business_started_pl,
    data -> 'properties' ->> 'year_business_started_sr' as year_business_started_sr,
    data -> 'properties' ->> 'year_trained_on_uf' as year_trained_on_uf,
    data -> 'properties' ->> 'yes_provide_details_bga' as yes_provide_details_bga,
    data -> 'properties' ->> 'your_target_market_bga' as your_target_market_bga,
    data -> 'properties' ->> 'if_yes_indicate_the_reasons_apa' as if_yes_indicate_the_reasons_apa,
    data -> 'properties' ->> 'county_of_apprenticeship_provider_apr' as county_of_apprenticeship_provider_apr,
    data -> 'properties' ->> 'Does_the_mentee_calculate_business_costs_before_setting_prices_bm' as Does_the_mentee_calculate_business_costs_before_setting_prices_bm,
    data -> 'properties' ->> 'if_no_indicate_the_reasons_apa' as if_no_indicate_the_reasons_apa,
    data -> 'properties' ->> 'is_the_institute_recommended_for_partnership_apa' as is_the_institute_recommended_for_partnership_apa,
    data -> 'properties' ->> 'sub-county_located_apbl' as sub_county_located_apbl,
    data -> 'properties' ->> 'sub-county_dc' as sub_county_dc,
    data -> 'properties' ->> 'county_apprenticeship_training_uf' as county_apprenticeship_training_uf,
    data -> 'properties' ->> 'county_of_apprenticeship_apr' as county_of_apprenticeship_apr,
    data -> 'properties' ->> 'did_participant_complete_the_traininng_placement_opportunity_tc' as did_participant_complete_the_traininng_placement_opportunity_tc,
    data -> 'properties' ->> 'during_your_interactions_at_the_tvet_did_you_experience_any_form_of_discrimination_abuse_harrassment_tvbl' as during_your_interactions_at_the_tvet_did_you_experience_any_form_of_discrimination_abuse_harrassment_tvbl,
    data -> 'properties' ->> 'on_rate_does_applicantgroup_have_ability_to_leverage_finances_bga' as on_rate_does_applicantgroup_have_ability_to_leverage_finances_bga,
    data -> 'properties' ->> 'solutions_agreed_to_be_implemented_to_address_challenges_bm' as solutions_agreed_to_be_implemented_to_address_challenges_bm,
    data -> 'properties' ->> 'whether_the_mentee_calculates_business_cost_before_setting_prices_bm' as whether_the_mentee_calculates_business_cost_before_setting_prices_bm,
    
    -- ========================================
    -- COWORKING MISSING FIELDS - ADDED
    -- ========================================
    -- Critical fields for coworking space analysis
    data -> 'properties' ->> 'users_fullname' as users_fullname,
    data -> 'properties' ->> 'fullname' as fullname_csr,
    data -> 'properties' ->> 'purpose_for_using_csf' as purpose_for_using_csf,
    data -> 'properties' ->> 'training_or_service' as training_or_service_csf,
    data -> 'properties' ->> 'using_coworking_for_living' as using_coworking_for_living_csr,
    data -> 'properties' ->> 'number_of_visitors' as number_of_visitors,
    data -> 'properties' ->> 'coworking_space_facility' as coworking_space_facility,
    data -> 'properties' ->> 'shofco_training' as shofco_training_csf,
    data -> 'properties' ->> 'purpose_of_visit' as purpose_of_visit
    

    -- ========================================
    -- EMPTY COLUMNS IN SOURCE (commented out)
    -- ========================================
    -- The following columns were found to have 0 non-null values in the source data
    -- and have been commented out to reduce model complexity:

    -- data -> 'properties' ->> 'alternative_phone_number_csf' as alternative_phone_number_csf,
    -- data -> 'properties' ->> 'external_id' as external_id,
    -- data -> 'properties' ->> 'name_csr' as name_csr,
    -- data -> 'properties' ->> 'name_dir' as name_dir,
    -- data -> 'properties' ->> 'name_dka' as name_dka,
    -- data -> 'properties' ->> 'name_bg' as name_bg,
    -- data -> 'properties' ->> 'name_bga' as name_bga,

FROM {{ source('staging_sl', 'zzz_case') }}
{% if is_incremental() %}
  WHERE data ->> 'date_modified' > (SELECT MAX(date_modified) FROM {{ this }})
{% endif %}
