{{ 
    config(
        materialized='table',
        unique_key='case_id',
        tags=['staging', 'sl_staging', 'commcare_extraction', 'sl']
    ) 
}}

with raw_cases as (
    select
        data ->> 'case_id' as case_id,
        COALESCE(data -> 'properties' ->> 'date_of_registration', data -> 'properties' ->> 'date_of_registration_dir') as date_of_registration_raw,
        data -> 'properties' ->> 'pp_unique_id' as pp_unique_id,
        coalesce(
            data -> 'properties' ->> 'participant_full-name_dir',
            data -> 'properties' ->> 'pp_fullname',
            data -> 'properties' ->> 'pp_fullname_dir',
            data -> 'properties' ->> 'name_sp',
            data -> 'properties' ->> 'name_sr',
            data -> 'properties' ->> 'name_tc',
            data -> 'properties' ->> 'name_pl',
            data -> 'properties' ->> 'name_psr',
            data -> 'properties' ->> 'users_fullname',
            data -> 'properties' ->> 'fullname',
            data -> 'properties' ->> 'fullname_csr'
        ) as pp_fullname,
        data -> 'properties' ->> 'profession_of_facilitator_psr' as profession_of_facilitator_psr,
        data -> 'properties' ->> 'psychosocial_facilitator_psr' as psychosocial_facilitator_psr,
        coalesce(
            data -> 'properties' ->> 'pp_sex',
            data -> 'properties' ->> 'sex_csf',
            data -> 'properties' ->> 'sex_dir',
            data -> 'properties' ->> 'sex_uid',
            data -> 'properties' ->> 'gender_bm',
            data -> 'properties' ->> 'gender_csf',
            data -> 'properties' ->> 'gender_hh_dka'
        ) as gender_raw,
        COALESCE(
            data -> 'properties' ->> 'do_you_have_children_sr',
            data -> 'properties' ->> 'do_you_have_children_uf'
        ) as do_you_have_children,
        coalesce(
            data -> 'properties' ->> 'nationality_csf',
            data -> 'properties' ->> 'nationality_dir'
        ) as nationality,
        coalesce(
            data -> 'properties' ->> 'participants_refugee_type_dir',
            data -> 'properties' ->> 'refugee_type_dir'
        ) as refugee_type,
        data -> 'properties' ->> 'kenyan_national_id_number_dir' as kenyan_national_id_number_dir,
        coalesce(
            data -> 'properties' ->> 'county_dir',
            data -> 'properties' ->> 'participants_county_of_residence_dir',
            data -> 'properties' ->> 'pp_shofco_county',
            data -> 'properties' ->> 'county_bm',
            data -> 'properties' ->> 'county_int',
            data -> 'properties' ->> 'coworking_county_csr'
        ) AS county,
        coalesce(
            data -> 'properties' ->> 'pp_shofco_subcounty',
            data -> 'properties' ->> 'subcounty_apprenticeship_provider_apr',
            data -> 'properties' ->> 'subcounty_bm',
            data -> 'properties' ->> 'subcounty_business_bga',
            data -> 'properties' ->> 'subcounty_business_located_bga',
            data -> 'properties' ->> 'subcounty_coworking_site_csf',
            data -> 'properties' ->> 'sub_county_of_institution_ttia',
            data -> 'properties' ->> 'sub-county_of_shofco_site_dir',
            data -> 'properties' ->> 'subcounty_shofco_site_dir',
            data -> 'properties' ->> 'coworking_subcounty_csr'
        ) as subcounty,
        coalesce(
            data -> 'properties' ->> 'pp_ahofco_ward',
            data -> 'properties' ->> 'ward_bm',
            data -> 'properties' ->> 'ward_business_bga',
            data -> 'properties' ->> 'ward_business_located_bga',
            data -> 'properties' ->> 'ward_coworking_site_csf',
            data -> 'properties' ->> 'ward_dc',
            data -> 'properties' ->> 'ward_dir',
            data -> 'properties' ->> 'ward_located_apbl',
            data -> 'properties' ->> 'ward_of_shofco_site_dir',
            data -> 'properties' ->> 'ward_of_the_institution_ttia',
            data -> 'properties' ->> 'ward_shofco_site_dir',
            data -> 'properties' ->> 'coworking_ward_csr'
        ) as ward,
        data -> 'properties' ->> 'coworking_county_csr' as coworking_county_csr,
        data -> 'properties' ->> 'coworking_subcounty_csr' as coworking_subcounty_csr,
        data -> 'properties' ->> 'coworking_ward_csr' as coworking_ward_csr,
        coalesce(
            data -> 'properties' ->> 'primary_phone_number_dir',
            data -> 'properties' ->> 'primary_phone_number_csf'
        ) as primary_phone_number,
        coalesce(
            data -> 'properties' ->> 'is_plwd',
            data -> 'properties' ->> 'is_plwd_csf',
            data -> 'properties' ->> 'is_pwd',
            data -> 'properties' ->> 'is_pwd_csf',
            data -> 'properties' ->> 'is_pwd_tvbl'
        ) as is_pwd,
        coalesce(
            data -> 'properties' ->> 'type_of_disability_dir',
            data -> 'properties' ->> 'type_of_disability',
            data -> 'properties' ->> 'type_of_disability_tvbl'
        ) as type_of_disability_dir,
        data -> 'properties' ->> 'apprenticeship_provider_apr' as apprenticeship_provider_apr,
        data -> 'properties' ->> 'skill_enrolled_apr' as skill_enrolled_apr,
        data -> 'properties' ->> 'placement_date_apr' as placement_date_apr_raw,
        data -> 'properties' ->> 'grant_amount_bg' as grant_amount_bg,
        data -> 'properties' ->> 'type_of_business_you_operate_bga' as type_of_business_you_operate_bga,
        data -> 'properties' ->> 'mark_the_location_of_the_business' as mark_the_location_of_the_business_raw,
        data -> 'properties' ->> 'gps_of_business_location_apbl' as gps_of_business_location_apbl_raw,
        data -> 'properties' ->> 'location_of_institute_ttia' as location_of_institution_ttia_raw,
        data -> 'properties' ->> 'date_grant_allocated_bg' as date_grant_allocated_bg_raw,
        data -> 'properties' ->> 'digital_literacy_dl' as digital_literacy_dl,
        data -> 'properties' ->> 'start_date_dl' as start_date_dl_raw,
        data -> 'properties' ->> 'advanced_it_start_date_dl' as advanced_it_start_date_dl_raw,
        data -> 'properties' ->> 'advanced_it_completion_date_dl' as advanced_it_completion_date_dl_raw,
        data -> 'properties' ->> 'completion_date_dl' as completion_date_dl_raw,
        data -> 'properties' ->> 'final_exams_tc' as final_exams_tc,
        data -> 'properties' ->> 'dignity_package_helpful_dka' as dignity_package_helpful_dka,
        data -> 'properties' ->> 'how_helpful_course' as how_helpful_course,
        data -> 'properties' ->> 'how_helpful_course_tc' as how_helpful_course_tc,
        data -> 'properties' ->> 'how_helpful_was_upskilling_uc' as how_helpful_was_upskilling_uc,
        data -> 'properties' ->> 'Why_not_helpful_tc' as why_not_helpful_tc,
        data -> 'properties' ->> 'why_not_helpful_uc' as why_not_helpful_uc,
        data -> 'properties' ->> 'how_helpful_course_tvet' as how_helpful_course_tvet,
        data -> 'properties' ->> 'recommend_training_tvet' as recommend_training_tvet,
        data -> 'properties' ->> 'start_date_ent' as start_date_ent_raw,
        data -> 'properties' ->> 'completion_date_ent' as completion_date_ent_raw,
        data -> 'properties' ->> 'interest_in_sales_work_ent' as interest_in_sales_work_ent,
        data -> 'properties' ->> 'support_to_help_succeed_as_entrepreneur_sr' as support_to_help_succeed_as_entrepreneur_sr,
        data -> 'properties' ->> 'start_date_int' as start_date_int_raw,
        data -> 'properties' ->> 'completion_date_int' as completion_date_int_raw,
        data -> 'properties' ->> 'income_on_average_pl' as income_on_average_pl,
        data -> 'properties' ->> 'placement_opportunity_pl' as placement_opportunity_pl,
        data -> 'properties' ->> 'date_first_visit_bm' as date_first_visit_bm_raw,
        data -> 'properties' ->> 'date_of_second_visit_bm' as date_of_second_visit_bm_raw,
        data -> 'properties' ->> 'date_of_visit_csf' as date_of_visit_csf_raw,
        data -> 'properties' ->> 'date_of_visit_csr' as date_of_visit_csr_raw,
        data -> 'properties' ->> 'date_of_birth_csf' as date_of_birth_csf,
        data -> 'properties' ->> 'age_in_years_csf' as age_in_years_csf,
        data -> 'properties' ->> 'first_name_csf' as first_name_csf,
        data -> 'properties' ->> 'second_name_csf' as second_name_csf,
        data -> 'properties' ->> 'how_many_csf' as how_many_csf,
        data -> 'properties' ->> 'time_in_csf' as time_in_csf,
        data -> 'properties' ->> 'time_in_csr' as time_in_csr,
        data -> 'properties' ->> 'time_out_csf' as time_out_csf,
        data -> 'properties' ->> 'time_out_csr' as time_out_csr,
        data -> 'properties' ->> 'using_coworking_for_a_living_csr' as using_coworking_for_a_living_csr,
        data -> 'properties' ->> 'using_coworking_to_earn_a_living_csf' as using_coworking_to_earn_a_living_csf,
        data -> 'properties' ->> 'what_visitor_is_using_csf' as what_visitor_is_using_csf,
        data -> 'properties' ->> 'what_visitor_is_using_csr' as what_visitor_is_using_csr,
        data -> 'properties' ->> 'purpose_for_using_csf' as purpose_for_using_csf,
        data -> 'properties' ->> 'coworking_space_facility' as coworking_space_facility,
        data -> 'properties' ->> 'swep_handcraft_center-hc' as swep_handcraft_center_hc,
        data -> 'properties' ->> 'start_date_hc' as start_date_hc_raw,
        data -> 'properties' ->> 'completion_date_hc' as completion_date_hc_raw,
        coalesce(
            data -> 'properties' ->> 'handcraft_training_type_hc',
            data -> 'properties' ->> 'handcraft_training_type_sr'
        ) as handcraft_training_type_hc,
        data -> 'properties' ->> 'swep-iga-center-iga' as swep_iga_center_iga,
        data -> 'properties' ->> 'start_date_iga' as start_date_iga_raw,
        data -> 'properties' ->> 'completion_date_iga' as completion_date_iga_raw,
        data -> 'properties' ->> 'training_type_iga' as training_type_iga,
        data -> 'properties' ->> 'swep_tailoring_center_st' as swep_tailoring_center_st,
        data -> 'properties' ->> 'start_date_of_training_st' as start_date_of_training_st_raw,
        data -> 'properties' ->> 'expected_end_date_of_training_st' as expected_end_date_of_training_st_raw,
        coalesce(
            data -> 'properties' ->> 'training_session_st',
            data -> 'properties' ->> 'training_session_sr'
        ) as training_session_st,
        data -> 'properties' ->> 'name_of_institution_tvet' as old_institution,
        data -> 'properties' ->> 'name_of_facilitator' as name_of_facilitator,
        coalesce(
        data -> 'properties' ->> 'course_enrolled_tvet',
        data -> 'properties' ->> 'other_course_tvet'
        ) as course_enrolled_tvet,
        data -> 'properties' ->> 'start_date_tvet' as start_date_tvet_raw,
        case
            when coalesce(data -> 'properties' ->> 'completion_date_tvet',
                          data -> 'properties' ->> 'completion_tvet') in ('31/4/2025', '31/04/2025') then null
            else coalesce(
                data -> 'properties' ->> 'completion_date_tvet',
                data -> 'properties' ->> 'completion_tvet'
            )
        end as completion_date_tvet_raw,
        coalesce(
            data -> 'properties' ->> 'nita_exams',
            data -> 'properties' ->> 'nita_exams_tc'
        ) as nita_exams
    from {{ source('staging_sl', 'zzz_case') }}
    where data -> 'properties' ->> 'case_type' = 'sl_new'
),
prepared_cases as (
select
    case_id,
        {{ validate_date('date_of_registration_raw') }} as date_of_registration,
        pp_unique_id,
        pp_fullname,
        profession_of_facilitator_psr,
        psychosocial_facilitator_psr,
        {{ normalize_gender('gender_raw') }} as gender,
        do_you_have_children,
        nationality,
        refugee_type,
        kenyan_national_id_number_dir,
        county,
        subcounty,
        ward,
        coworking_county_csr,
        coworking_subcounty_csr,
        coworking_ward_csr,
        primary_phone_number,
        right(primary_phone_number, 8) as phone_last_8_digits,
        is_pwd,
        type_of_disability_dir,
        case
            when lower(trim({{ normalize_gender('gender_raw') }})) = 'female' and lower(trim(do_you_have_children)) = 'yes' then 'yes'
            when {{ normalize_gender('gender_raw') }} is null or trim({{ normalize_gender('gender_raw') }}) = '' or do_you_have_children is null or trim(do_you_have_children) = '' then 'don''t know'
            when lower(trim(do_you_have_children)) = 'no' then 'no'
            else 'no'
        end as is_young_mother,
        apprenticeship_provider_apr,
        type_of_business_you_operate_bga,
        skill_enrolled_apr,
        {{ validate_date('placement_date_apr_raw') }} as placement_date_apr,
        grant_amount_bg,
        {{ validate_date('date_grant_allocated_bg_raw') }} as date_grant_allocated_bg,

        mark_the_location_of_the_business_raw,

        case 
            when mark_the_location_of_the_business_raw is not null
            then split_part(mark_the_location_of_the_business_raw, ' ', 1)::double precision
        end as business_latitude,

        case 
            when mark_the_location_of_the_business_raw is not null
            then split_part(mark_the_location_of_the_business_raw, ' ', 2)::double precision
        end as business_longitude,

        case 
            when mark_the_location_of_the_business_raw is not null
            then split_part(mark_the_location_of_the_business_raw, ' ', 3)::double precision
        end as business_altitude,

        case 
            when mark_the_location_of_the_business_raw is not null
            then split_part(mark_the_location_of_the_business_raw, ' ', 4)::double precision
        end as business_accuracy,

        gps_of_business_location_apbl_raw,

        case
            when gps_of_business_location_apbl_raw is not null
            then split_part(gps_of_business_location_apbl_raw, ' ', 1)::double precision
        end as apprenticeship_latitude,

        case
            when gps_of_business_location_apbl_raw is not null
            then split_part(gps_of_business_location_apbl_raw, ' ', 2)::double precision
        end as apprenticeship_longitude,

        case
            when gps_of_business_location_apbl_raw is not null
            then split_part(gps_of_business_location_apbl_raw, ' ', 3)::double precision
        end as apprenticeship_altitude,

        case
            when gps_of_business_location_apbl_raw is not null
            then split_part(gps_of_business_location_apbl_raw, ' ', 4)::double precision
        end as apprenticeship_accuracy,

        location_of_institution_ttia_raw,

        case
            when location_of_institution_ttia_raw is not null
            then split_part(location_of_institution_ttia_raw, ' ', 1)::double precision
        end as tvet_latitude,

        case
            when location_of_institution_ttia_raw is not null
            then split_part(location_of_institution_ttia_raw, ' ', 2)::double precision
        end as tvet_longitude,

        case
            when location_of_institution_ttia_raw is not null
            then split_part(location_of_institution_ttia_raw, ' ', 3)::double precision
        end as tvet_altitude,

        case
            when location_of_institution_ttia_raw is not null
            then split_part(location_of_institution_ttia_raw, ' ', 4)::double precision
        end as tvet_accuracy,

        digital_literacy_dl,
        {{ validate_date('start_date_dl_raw') }} as start_date_dl,
        {{ validate_date('advanced_it_start_date_dl_raw') }} as advanced_it_start_date_dl,
        {{ validate_date('advanced_it_completion_date_dl_raw') }} as advanced_it_completion_date_dl,
        {{ validate_date('completion_date_dl_raw') }} as completion_date_dl,
        final_exams_tc,
        dignity_package_helpful_dka,
        how_helpful_course,
        how_helpful_course_tc,
        how_helpful_was_upskilling_uc,
        why_not_helpful_tc,
        why_not_helpful_uc,
        how_helpful_course_tvet,
        recommend_training_tvet,
        {{ validate_date('start_date_ent_raw') }} as start_date_ent,
        {{ validate_date('completion_date_ent_raw') }} as completion_date_ent,
        interest_in_sales_work_ent,
        {{ validate_date('start_date_int_raw') }} as start_date_int,
        {{ validate_date('completion_date_int_raw') }} as completion_date_int,
        income_on_average_pl,
        placement_opportunity_pl,
        {{ validate_date('date_first_visit_bm_raw') }} as date_first_visit_bm,
        {{ validate_date('date_of_second_visit_bm_raw') }} as date_of_second_visit_bm,
        {{ validate_date('date_of_visit_csf_raw') }} as date_of_visit_csf,
        {{ validate_date('date_of_visit_csr_raw') }} as date_of_visit_csr,
        date_of_birth_csf,
        age_in_years_csf,
        first_name_csf,
        second_name_csf,
        how_many_csf,
        time_in_csf,
        time_in_csr,
        time_out_csf,
        time_out_csr,
        using_coworking_for_a_living_csr,
        using_coworking_to_earn_a_living_csf,
        what_visitor_is_using_csf,
        what_visitor_is_using_csr,
        purpose_for_using_csf,
        coworking_space_facility,
        swep_handcraft_center_hc,
        {{ validate_date('start_date_hc_raw') }} as start_date_hc,
        {{ validate_date('completion_date_hc_raw') }} as completion_date_hc,
        handcraft_training_type_hc,
        swep_iga_center_iga,
        {{ validate_date('start_date_iga_raw') }} as start_date_iga,
        {{ validate_date('completion_date_iga_raw') }} as completion_date_iga,
        training_type_iga,
        swep_tailoring_center_st,
        {{ validate_date('start_date_of_training_st_raw') }} as start_date_of_training_st,
        {{ validate_date('expected_end_date_of_training_st_raw') }} as expected_end_date_of_training_st,
        training_session_st,
        old_institution,
        name_of_facilitator,
        course_enrolled_tvet,
        {{ validate_date('start_date_tvet_raw') }} as start_date_tvet,
        {{ validate_date('completion_date_tvet_raw') }} as completion_date_tvet,
        nita_exams,
        lower(trim(pp_unique_id)) as norm_pp_unique_id,
        regexp_replace(lower(coalesce(pp_fullname, '')), '\s+', ' ', 'g') as norm_pp_fullname,
        lower(trim(kenyan_national_id_number_dir)) as norm_kenyan_id,
        case
            when county is null or trim(county) = '' then null
            else
                case
                    when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'kiii' then 'kilifi'
                    when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'buia' then 'busia'
                    when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'homabay' then 'homa bay'
                    when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'kiumu' then 'kisumu'
                    when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'mombaa' then 'mombasa'
                    when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'uaingihu' then 'uain gihu'
                    when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'trannzoia' then 'tran nzoia'
                    when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'taitataveta' then 'taita taveta'
                    else lower(trim(county))
                end
        end as norm_county
    from raw_cases
),

deduplicated_cases as (
    select
        min(nullif(trim(case_id), '')) as case_id,
        max(date_of_registration) as date_of_registration,
        max(nullif(trim(pp_unique_id), '')) as pp_unique_id,
        max(nullif(trim(pp_fullname), '')) as pp_fullname,
        max(nullif(trim(profession_of_facilitator_psr), '')) as profession_of_facilitator_psr,
        max(nullif(trim(psychosocial_facilitator_psr), '')) as psychosocial_facilitator_psr,
        max(nullif(trim(kenyan_national_id_number_dir), '')) as kenyan_national_id_number_dir,
        max(nullif(trim(gender), '')) as gender,
        max(nullif(trim(nationality), '')) as nationality,
        max(nullif(trim(refugee_type), '')) as refugee_type,
        max(nullif(trim(county), '')) as county,
        max(nullif(trim(subcounty), '')) as subcounty,
        max(nullif(trim(ward), '')) as ward,
        max(nullif(trim(coworking_county_csr), '')) as coworking_county_csr,
        max(nullif(trim(coworking_subcounty_csr), '')) as coworking_subcounty_csr,
        max(nullif(trim(coworking_ward_csr), '')) as coworking_ward_csr,
        max(nullif(trim(primary_phone_number), '')) as primary_phone_number,
        max(nullif(trim(phone_last_8_digits), '')) as phone_last_8_digits,
        CASE
            WHEN max(CASE WHEN lower(nullif(trim(is_pwd), '')) = 'yes' THEN 1 ELSE 0 END) = 1
                THEN 'yes'
            ELSE max(nullif(trim(is_pwd), ''))
        END as is_pwd,
        max(nullif(trim(type_of_disability_dir), '')) as type_of_disability_dir,
        CASE
            WHEN max(CASE WHEN lower(nullif(trim(is_young_mother), '')) = 'yes' THEN 1 ELSE 0 END) = 1 THEN 'yes'
            WHEN max(CASE WHEN lower(nullif(trim(is_young_mother), '')) = 'don''t know' THEN 1 ELSE 0 END) = 1 THEN 'don''t know'
            ELSE max(nullif(trim(is_young_mother), ''))
        END as is_young_mother,
        max(nullif(trim(apprenticeship_provider_apr), '')) as apprenticeship_provider_apr,
        max(nullif(trim(skill_enrolled_apr), '')) as skill_enrolled_apr,
        max(placement_date_apr) as placement_date_apr,
        max(nullif(trim(grant_amount_bg), '')) as grant_amount_bg,
        max(date_grant_allocated_bg) as date_grant_allocated_bg,
        max(nullif(trim(type_of_business_you_operate_bga), '')) as type_of_business_you_operate_bga,
        max(mark_the_location_of_the_business_raw) as mark_the_location_of_the_business_raw,
        max(business_latitude) as business_latitude,
        max(business_longitude) as business_longitude,
        max(business_altitude) as business_altitude,
        max(business_accuracy) as business_accuracy,
        max(gps_of_business_location_apbl_raw) as gps_of_business_location_apbl_raw,
        max(apprenticeship_latitude) as apprenticeship_latitude,
        max(apprenticeship_longitude) as apprenticeship_longitude,
        max(apprenticeship_altitude) as apprenticeship_altitude,
        max(apprenticeship_accuracy) as apprenticeship_accuracy,
        max(location_of_institution_ttia_raw) as location_of_institution_ttia_raw,
        max(tvet_latitude) as tvet_latitude,
        max(tvet_longitude) as tvet_longitude,
        max(tvet_altitude) as tvet_altitude,
        max(tvet_accuracy) as tvet_accuracy,
        max(nullif(trim(digital_literacy_dl), '')) as digital_literacy_dl,
        max(start_date_dl) as start_date_dl,
        max(advanced_it_start_date_dl) as advanced_it_start_date_dl,
        max(advanced_it_completion_date_dl) as advanced_it_completion_date_dl,
        max(completion_date_dl) as completion_date_dl,
        max(nullif(trim(final_exams_tc), '')) as final_exams_tc,
        max(nullif(trim(dignity_package_helpful_dka), '')) as dignity_package_helpful_dka,
        max(nullif(trim(how_helpful_course), '')) as how_helpful_course,
        max(nullif(trim(how_helpful_course_tc), '')) as how_helpful_course_tc,
        max(nullif(trim(how_helpful_was_upskilling_uc), '')) as how_helpful_was_upskilling_uc,
        max(nullif(trim(why_not_helpful_tc), '')) as why_not_helpful_tc,
        max(nullif(trim(why_not_helpful_uc), '')) as why_not_helpful_uc,
        max(nullif(trim(how_helpful_course_tvet), '')) as how_helpful_course_tvet,
        max(nullif(trim(recommend_training_tvet), '')) as recommend_training_tvet,
        max(start_date_ent) as start_date_ent,
        max(completion_date_ent) as completion_date_ent,
        max(nullif(trim(interest_in_sales_work_ent), '')) as interest_in_sales_work_ent,
        max(start_date_int) as start_date_int,
        max(completion_date_int) as completion_date_int,
        max(nullif(trim(income_on_average_pl), '')) as income_on_average_pl,
        max(nullif(trim(placement_opportunity_pl), '')) as placement_opportunity_pl,
        max(date_first_visit_bm) as date_first_visit_bm,
        max(date_of_second_visit_bm) as date_of_second_visit_bm,
        max(date_of_visit_csf) as date_of_visit_csf,
        max(date_of_visit_csr) as date_of_visit_csr,
        max(nullif(trim(date_of_birth_csf), '')) as date_of_birth_csf,
        max(nullif(trim(age_in_years_csf), '')) as age_in_years_csf,
        max(nullif(trim(first_name_csf), '')) as first_name_csf,
        max(nullif(trim(second_name_csf), '')) as second_name_csf,
        max(nullif(trim(how_many_csf), '')) as how_many_csf,
        max(nullif(trim(time_in_csf), '')) as time_in_csf,
        max(nullif(trim(time_in_csr), '')) as time_in_csr,
        max(nullif(trim(time_out_csf), '')) as time_out_csf,
        max(nullif(trim(time_out_csr), '')) as time_out_csr,
        max(nullif(trim(using_coworking_for_a_living_csr), '')) as using_coworking_for_a_living_csr,
        max(nullif(trim(using_coworking_to_earn_a_living_csf), '')) as using_coworking_to_earn_a_living_csf,
        max(nullif(trim(what_visitor_is_using_csf), '')) as what_visitor_is_using_csf,
        max(nullif(trim(what_visitor_is_using_csr), '')) as what_visitor_is_using_csr,
        max(nullif(trim(purpose_for_using_csf), '')) as purpose_for_using_csf,
        max(nullif(trim(coworking_space_facility), '')) as coworking_space_facility,
        max(nullif(trim(swep_handcraft_center_hc), '')) as swep_handcraft_center_hc,
        max(start_date_hc) as start_date_hc,
        max(completion_date_hc) as completion_date_hc,
        max(nullif(trim(handcraft_training_type_hc), '')) as handcraft_training_type_hc,
        max(nullif(trim(swep_iga_center_iga), '')) as swep_iga_center_iga,
        max(start_date_iga) as start_date_iga,
        max(completion_date_iga) as completion_date_iga,
        max(nullif(trim(training_type_iga), '')) as training_type_iga,
        max(nullif(trim(swep_tailoring_center_st), '')) as swep_tailoring_center_st,
        max(start_date_of_training_st) as start_date_of_training_st,
        max(expected_end_date_of_training_st) as expected_end_date_of_training_st,
        max(nullif(trim(training_session_st), '')) as training_session_st,
        max(nullif(trim(old_institution), '')) as old_institution,
        max(nullif(trim(name_of_facilitator), '')) as name_of_facilitator,
        max(nullif(trim(course_enrolled_tvet), '')) as course_enrolled_tvet,
        max(start_date_tvet) as start_date_tvet,
        max(completion_date_tvet) as completion_date_tvet,
        CASE
            WHEN max(CASE WHEN lower(nullif(trim(nita_exams), '')) = 'yes' THEN 1 ELSE 0 END) = 1
                THEN 'yes'
            ELSE max(nullif(trim(nita_exams), ''))
        END as nita_exams
    from prepared_cases
    group by
        coalesce(norm_pp_unique_id, case_id),
        coalesce(norm_pp_fullname, case_id),
        coalesce(norm_kenyan_id, case_id),
        coalesce(phone_last_8_digits, case_id),
        coalesce(norm_county, case_id)
),

skill_sector_mapping as (
    select skill_enrolled_apr, skill_name, sector_name
    from (values
        -- Automotive Engineering
        ('spray_painter_automotive_engineering_sector',                          'Spray Painter',                            'Automotive Engineering'),
        ('panel_beater_automotive_engineering_sector',                          'Panel Beater',                             'Automotive Engineering'),
        ('plant_mechanic_automotive_engineering_sector',                        'Plant Mechanic',                           'Automotive Engineering'),
        ('electronic_mechanics_automotive_engineering_sector',                  'Electronic Mechanics',                     'Automotive Engineering'),
        ('motor_vehicle_mechanic_automotive_engineering_sector',                'Motor Vehicle Mechanic',                   'Automotive Engineering'),
        ('motor_vehicle_electrician_automotive_engineering_sector',             'Motor Vehicle Electrician',                'Automotive Engineering'),
        ('upholstery_automotive_engineering_sector',                            'Upholstery',                               'Automotive Engineering'),
        -- Building and Construction
        ('molder_building__construction_sector',                                'Molder',                                   'Building and Construction'),
        ('refrigeration_and_air_conditioning_building__construction_sector',    'Refrigeration and Air Conditioning',       'Building and Construction'),
        ('painter_decorator_building__construction_sector',                     'Painter Decorator',                        'Building and Construction'),
        ('cabinet_maker_building__construction_sector',                         'Cabinet Maker',                            'Building and Construction'),
        ('carpentry_and_joinery_building__construction_sector',                 'Carpentry and Joinery',                    'Building and Construction'),
        ('electrical_fitter_building__construction_sector',                     'Electrical Fitter',                        'Building and Construction'),
        ('sign_writer_building__construction_sector',                           'Sign Writer',                              'Building and Construction'),
        ('general_fitter_building__construction_sector',                        'General Fitter',                           'Building and Construction'),
        ('pipe_fitter_building__construction_sector',                           'Pipe Fitter',                              'Building and Construction'),
        ('masonry_building__construction_sector',                               'Masonry',                                  'Building and Construction'),
        ('plumber_building__construction_sector',                               'Plumber',                                  'Building and Construction'),
        ('arc_welder_building__construction_sector',                            'Arc Welder',                               'Building and Construction'),
        ('gas_welder_building__construction_sector',                            'Gas Welder',                               'Building and Construction'),
        ('woodcarver_and_wood_machinist_building__construction_sector',         'Woodcarver and Wood Machinist',             'Building and Construction'),
        ('sheet_metal_building__construction_sector',                           'Sheet Metal',                              'Building and Construction'),
        ('solar_photovoltaic_building__construction_sector',                    'Solar Photovoltaic',                       'Building and Construction'),
        ('electrical_wireman_building__construction_sector',                    'Electrical Wireman',                       'Building and Construction'),
        ('tiling_building__construction_sector',                                'Tiling',                                   'Building and Construction'),
        -- Hospitality
        ('food_and_beverage_hospitality_sector',                                'Food and Beverage',                        'Hospitality'),
        ('baking_hospitality_sector',                                           'Baking',                                   'Hospitality'),
        ('catering_hospitality_sector',                                         'Catering',                                 'Hospitality'),
        ('housekeeping_and_laundry_hospitality_sector',                         'Housekeeping and Laundry',                 'Hospitality'),
        -- Agribusiness
        ('horticulture_farm_management_agribusiness_sector',                    'Horticulture Farm Management',             'Agribusiness'),
        ('vegetable_production_and_aquaculture_agribusiness_sector',            'Vegetable Production and Aquaculture',     'Agribusiness'),
        ('dairy_farm_management_agribusiness_sector',                           'Dairy Farm Management',                    'Agribusiness'),
        -- Media
        ('photography__videography_media_sector',                               'Photography and Videography',              'Media'),
        -- Beauty Hairdressing and Textile
        ('tailoring_and_dressmaking_beautyhairdressing_and_textile_sector',     'Tailoring and Dressmaking',                'Beauty Hairdressing and Textile'),
        ('beauty_therapy_beautyhairdressing_and_textile_sector',                'Beauty Therapy',                           'Beauty Hairdressing and Textile'),
        ('hair_dressing_beautyhairdressing_and_textile_sector',                 'Hair Dressing',                            'Beauty Hairdressing and Textile'),
        -- ICT
        ('information_communication_and_technology_ict',                        'Information Communication and Technology', 'ICT'),
        -- Other
        ('other',                                                               'Other',                                    'Other')
    ) as t(skill_enrolled_apr, skill_name, sector_name)
),

institution_name_mapping as (
    select old_institution, institution_name
    from (values
        ('africa_institute_of research', 'African Institute of Research Development Studies-AIRADS'),
        ('African Institute of Research Development Studies-AIRADS', 'African Institute of Research Development Studies-AIRADS'),
        ('Ahero VTC', 'Ahero VTC'),
        ('Ahero vtc', 'Ahero VTC'),
        ('AHERO VTC', 'Ahero VTC'),
        ('ahero_vocational_trining_centre', 'Ahero VTC'),
        ('ahmed_shahame', 'Ahmed Shahame Mwidani TTI'),
        ('AIC', 'AIC Training Institute'),
        ('AIC NAIROBI TRAINING CENTRE', 'AIC Training Institute'),
        ('AIC Training Institute', 'AIC Training Institute'),
        ('aic_training', 'AIC Training Institute'),
        ('AIRAD', 'African Institute of Research Development Studies-AIRADS'),
        ('Akado vtc', 'AKADO VTC'),
        ('AKADO VTC', 'AKADO VTC'),
        ('akado_vtc', 'AKADO VTC'),
        ('AMAASE', 'Amaase vtc'),
        ('amaase_vtc', 'Amaase vtc'),
        ('AMAGORO', 'Amagoro'),
        ('amagoro_vtc', 'Amagoro'),
        ('Angaza vocational training college', 'Angaza vocational training college'),
        ('angaza_empowerment_training_center', 'Angaza Empowerment Training Center'),
        ('angaza_vocational', 'Angaza vocational training college'),
        ('Apokor', 'Apokor vtc'),
        ('archbishop_okoth_koru', 'ARCH BISHOP OKOTH KORU VTC'),
        ('AWENDO MARINDI', 'Awendo Marindi VTC'),
        ('Awendo Marindi VTC', 'Awendo Marindi VTC'),
        ('awendo_marindi', 'Awendo Marindi VTC'),
        ('BAHATI VTC', 'Bahati'),
        ('Bahati VTC', 'Bahati'),
        ('Bip college', 'Bips technical college'),
        ('BIPS technical college', 'Bips technical college'),
        ('BIPS TECHNICAL College', 'Bips technical college'),
        ('bips_technical_college', 'Bips technical college'),
        ('Bondo TTI', 'Bondo TTI'),
        ('bondo_tti', 'Bondo TTI'),
        ('BOYANI', 'Boyani VTC'),
        ('boyani_vtc', 'Boyani VTC'),
        ('builcon_technologies_kilifi', 'Builcon Technologies-Kilifi'),
        ('buildher', 'Buildher'),
        ('BUNYALA CNT', 'Bunyala tvc'),
        ('BUNYALA TTI', 'Bunyala tvc'),
        ('BUNYALA TVC', 'Bunyala tvc'),
        ('bunyala_tvc', 'Bunyala tvc'),
        ('burundu_cp', 'Burundu CP'),
        ('busagwa_vtc', 'Busagwa VTC'),
        ('Bushiangala TTI', 'Bushiangala TTI'),
        ('BUSHIANGALA VTC', 'Bushiangala TTI'),
        ('bushiangala_tti', 'Bushiangala TTI'),
        ('BUTERE', 'Butere TTI'),
        ('butere_tti', 'Butere TTI'),
        ('butula_vtc', 'Butula VTC'),
        ('Cambridge College', 'Cambridge college'),
        ('CAP-YEI Kisumu', 'Ujuzi Institute CAP-YEI Kisumu'),
        ('CAPYEI -Nairobi', 'Ujuzi Institute -CAPYEI -Nairobi'),
        ('CAPYEI COLLEGE -KISUMU', 'Ujuzi Institute CAP-YEI Kisumu'),
        ('Capyei kisumu', 'Ujuzi Institute CAP-YEI Kisumu'),
        ('capyei kisumu', 'Ujuzi Institute CAP-YEI Kisumu'),
        ('CAPYEI MOMBASA', 'Ujuzi Institute-CAPYEI Mombasa'),
        ('Capyei Mombasa', 'Ujuzi Institute-CAPYEI Mombasa'),
        ('Capyei Ujuzi Mombasa', 'Ujuzi Institute-CAPYEI Mombasa'),
        ('centurion_training', 'Centurion Training Institute'),
        ('Challa Vocational Training Center', 'Challa Vocational Training Center'),
        ('challa VTC', 'Challa Vocational Training Center'),
        ('CHALLA VTC', 'Challa Vocational Training Center'),
        ('Challa VTC', 'Challa Vocational Training Center'),
        ('challa_vocational_training', 'Challa Vocational Training Center'),
        ('CHAMINADE', 'Chaminade Training centre'),
        ('Chaminade', 'Chaminade Training centre'),
        ('Chaminade Training Center', 'Chaminade Training centre'),
        ('Chaminade training centre', 'Chaminade Training centre'),
        ('CHAMINADE TRAINING CENTRE', 'Chaminade Training centre'),
        ('Chaminade Training Centre', 'Chaminade Training centre'),
        ('chaminade_training_centre', 'Chaminade Training centre'),
        ('CHOMBELI', 'Chombeli vtc'),
        ('Chumvini Vocational Training Center', 'Chumvini Vocational Training Center'),
        ('Chumvini VTC', 'Chumvini Vocational Training Center'),
        ('chumvini_vocational_training', 'Chumvini Vocational Training Center'),
        ('CHWELE', 'Chwele'),
        ('Clips College', 'Clips college'),
        ('Consolata', 'Consolata Cathedral Institute'),
        ('Consolata 1111', 'Consolata Cathedral Institute'),
        ('Consolata Cathedral Institute', 'Consolata Cathedral Institute'),
        ('consolata_institute', 'Consolata Cathedral Institute'),
        ('DZITSONI VTI', 'Dzitsoni Vocational Centre'),
        ('dzitsoni_vocational', 'Dzitsoni Vocational Centre'),
        ('E-SMART', 'E-Smart vti'),
        ('EAST AFRICA INSTITUTE OF HOMECARE', 'East African Institute of Homecare management'),
        ('EAst AFRICA INSTITUTE OF HOMECARE', 'East African Institute of Homecare management'),
        ('EAST AFRICA INSTITUTE OF HOMECARE MANAGEMENT', 'East African Institute of Homecare management'),
        ('East African Institute', 'East African Institute of Homecare management'),
        ('east_african_institute', 'East African Institute of Homecare management'),
        ('Eastern Kenya Intergrated College', 'Eastern Kenya Intergrated College'),
        ('eastern_kenya_intergrated', 'Eastern Kenya Intergrated College'),
        ('ebukanga_vtc', 'Ebukanga VTC'),
        ('EBUSIRALO', 'Ebusiralo'),
        ('ebusiralo', 'Ebusiralo'),
        ('Eldoret Tourist', 'Eldoret tourism and professional college'),
        ('EMMUKUNZI', 'Emmukunzi'),
        ('emmukunzi', 'Emmukunzi'),
        ('enzai_vtc', 'Enzai VTC'),
        ('Ezesha Plus Institute', 'Ezesha plus'),
        ('Gathinga', 'Gathinga vtc'),
        ('GEDE VTI', 'Gede VTI'),
        ('Gichira', 'Gichira VTC'),
        ('gimamoi_ VTI', 'Gimamoi VTI'),
        ('Gitero', 'Gitero VTC'),
        ('givigoi', 'Givigoi'),
        ('GIVIGOI', 'Givigoi'),
        ('GOD NYINYO', 'God Nyinyo VTI'),
        ('GODOMA TTI', 'Godoma TTI'),
        ('godoma_tti', 'Godoma TTI'),
        ('GODOMATTI', 'Godoma TTI'),
        ('GREEN LIGHT VTC', 'Greenlight Dandora Vocational Training Centre'),
        ('green_light_dandora', 'Greenlight Dandora Vocational Training Centre'),
        ('Greenlight Dandora Vocational Training Centre', 'Greenlight Dandora Vocational Training Centre'),
        ('hambale', 'Hambale'),
        ('HOLY GHOST FATHERS INSTITUTE', 'HOLY GHOST FATHERS INSTITUTE'),
        ('holy_ghost_fathers', 'HOLY GHOST FATHERS INSTITUTE'),
        ('IMBEKE', 'Imbeke Charitable Trust VTC'),
        ('IMBEKE CHARITABLE Trust', 'Imbeke Charitable Trust VTC'),
        ('Imbeke Charitable Trust', 'Imbeke Charitable Trust VTC'),
        ('IMBEKE CHARITABLE TRUST', 'Imbeke Charitable Trust VTC'),
        ('Imbeke charitable trust', 'Imbeke Charitable Trust VTC'),
        ('Imbeke Charitable Trust VTC', 'Imbeke Charitable Trust VTC'),
        ('imbeke_charitable_trust', 'Imbeke Charitable Trust VTC'),
        ('IQRA FOUNDATION', 'IQRA FOUNDATION'),
        ('iqra_foundation', 'IQRA FOUNDATION'),
        ('JERICHO VTC', 'Jericho VTC'),
        ('jfc_munene_vtc', 'JFC Munene VTC'),
        ('Kababu VTC', 'Kababu VTC'),
        ('kababu_kababu', 'Kababu VTC'),
        ('KABRAS VTC', 'Kabras VTC'),
        ('kabras_vtc', 'Kabras VTC'),
        ('KAIMOSI', 'Kaimosi Friends VTC'),
        ('kaimosi_ friends_ vtc', 'Kaimosi Friends VTC'),
        ('KAKAMEGA COUNTY POLY', 'Kakamega County Polytechnic'),
        ('kakamega_county_polytechnic', 'Kakamega County Polytechnic'),
        ('Kakuyuni Vocational Centre', 'Kakuyuni Vocational Centre'),
        ('kakuyuni_vocational', 'Kakuyuni Vocational Centre'),
        ('KALOLENI VTI', 'Kaloleni VTC'),
        ('kaloleni_vtc', 'Kaloleni VTC'),
        ('KAMBE RIBE VTI', 'Kambe Ribe vocational Training Center'),
        ('kambe_ribe_vocational', 'Kambe Ribe vocational Training Center'),
        ('kamirithu_polytechnic', 'Kamirithu Polytechnic'),
        ('kamoro_vtc', 'Komoro VTC'),
        ('kandara_vtc', 'Kandara VTC'),
        ('Kangemi vocational institution', 'Kangemi Training centre'),
        ('Kangemi vocational training', 'Kangemi Training centre'),
        ('Kangemi Vocational training centre', 'Kangemi Training centre'),
        ('Kangemi vocational training centre', 'Kangemi Training centre'),
        ('KANGEMI VTC', 'Kangemi Training centre'),
        ('kangemi_training_centre', 'Kangemi Training centre'),
        ('kaplong_vtc', 'Kaplong VTC'),
        ('Karatina Vocational', 'Karatina Vocational'),
        ('Karatina VTC', 'Karatina Vocational'),
        ('karatina_vocational', 'Karatina Vocational'),
        ('Karrumo Technical Training Institute', 'Karumo Technical Institute'),
        ('KARUMO Technical Training Institue', 'Karumo Technical Institute'),
        ('Karumo training institute', 'Karumo Technical Institute'),
        ('KARUMO TTI', 'Karumo Technical Institute'),
        ('Karundu', 'Karundu VTI'),
        ('KATAKWA', 'Katakwa vtc'),
        ('katakwa_vtc', 'Katakwa vtc'),
        ('Katine Technical Training Institute', 'Katine Technical Training Institute'),
        ('katine_technical_training', 'Katine Technical Training Institute'),
        ('KATITO VTC', 'Katito VTC'),
        ('Katito VTC', 'Katito VTC'),
        ('katito_vtc', 'Katito VTC'),
        ('KCITI', 'KCITI VTC'),
        ('kciti_vtc', 'KCITI VTC'),
        ('KEROKA TECHNICAL INSTITUTE', 'Keroka TTI'),
        ('KEVEYE', 'Keveye vtc'),
        ('KHASOKO', 'Khasoko institute'),
        ('KHELELA', 'Khelela tti'),
        ('khwisero_county_polytechnic', 'Khwisero County Polytechnic'),
        ('kiajai_vocational_training_center', 'Kiajai vocational training center'),
        ('kicdt_kisumu', 'KICDT KISUMU'),
        ('KICDT- KISII', 'KICDT-Kisii'),
        ('kiharu_vtc', 'Kiharu VTC'),
        ('Kiirua technical college', 'Kiirua Technical Institute'),
        ('Kiirua Technical Training institute', 'Kiirua Technical Institute'),
        ('kiirua_technical_institute', 'Kiirua Technical Institute'),
        ('Kilimabogo School of Highway Technology', 'Kilimabogo VTC'),
        ('KIMININI VOCATIONAL TRAINING CENTRE', 'KIMININI VOCATIONAL TRAINING CENTRE'),
        ('kiminini_vocational', 'KIMININI VOCATIONAL TRAINING CENTRE'),
        ('kipsamumkut_vtc', 'Kipsamumkut VTC'),
        ('Kisauni Vocational Training Institute', 'KISAUNI POLYTECHNIC'),
        ('kisauni_polytechnic', 'KISAUNI POLYTECHNIC'),
        ('kisiwa_tti', 'Kisiwa TTI'),
        ('Komoro VTC', 'Komoro VTC'),
        ('Kongoni', 'Kongoni VTC'),
        ('Kongoni VTC', 'Kongoni VTC'),
        ('kongoni_tvc', 'Kongoni VTC'),
        ('Kwanza Vocational Training Center', 'Kwanza Vocational Training Center'),
        ('Kwanza VTC', 'Kwanza Vocational Training Center'),
        ('kwanza_vocational', 'Kwanza Vocational Training Center'),
        ('Langi Polytechnic', 'Langi Polytechnic'),
        ('Langi polytechnic', 'Langi Polytechnic'),
        ('langi_polytechnic', 'Langi Polytechnic'),
        ('Liganwa VTC', 'Liganwa VTI'),
        ('Lindtech', 'Lindtech College'),
        ('Lindtech College', 'Lindtech College'),
        ('LINDTECH COLLEGE', 'Lindtech College'),
        ('Lindtech college', 'Lindtech College'),
        ('lindtech_college', 'Lindtech College'),
        ('LOTEGO', 'Lotego VTC'),
        ('Lucy Onono VTC', 'Lucy Onono VTC'),
        ('LUGALA', 'Lugala Youth County Polytechnic'),
        ('Lugala County Polytechnic', 'Lugala Youth County Polytechnic'),
        ('lugala_youth_county', 'Lugala Youth County Polytechnic'),
        ('LUMAKANDA VTC', 'Lumakanda VTC'),
        ('lung''anyiro', 'Lung''anyiro'),
        ('Macalda VTC', 'Macalda VTC'),
        ('Machungwa VTC', 'Machungwa VTI'),
        ('mago', 'Mago'),
        ('Mahanaim', 'Mahanaim college'),
        ('mahanaim_college', 'Mahanaim college'),
        ('Mahaya VTC', 'Mahaya vtc'),
        ('Mariakani Vocational Centre', 'Mariakani Vocational Centre'),
        ('MARIAKANI VTI', 'Mariakani Vocational Centre'),
        ('mariakani_vocational', 'Mariakani Vocational Centre'),
        ('MARIANIST TRAINING INSTITUTE', 'MARIANIST TRAINING INSTITUTE'),
        ('marianist_training', 'MARIANIST TRAINING INSTITUTE'),
        ('Martins College', 'Martins College'),
        ('martins_college', 'Martins College'),
        ('Marwa VTC', 'Marwa VTC'),
        ('MASENO', 'Maseno'),
        ('maseno', 'Maseno'),
        ('MATHARE VTC', 'Mathare vtc'),
        ('Mathare VTC', 'Mathare vtc'),
        ('MATILI TTI', 'Matili TTI'),
        ('matili_tti', 'Matili TTI'),
        ('matungu_cp', 'Matungu CP'),
        ('Mavindini VTC', 'Mavindini vtc'),
        ('MAWEGO', 'Mawego vtc'),
        ('Mbaaini', 'Mbaaini VTC'),
        ('Meru national polytechnic', 'Meru Technical Institute'),
        ('Meru National polytechnic', 'Meru Technical Institute'),
        ('Meru National Polytechnic', 'Meru Technical Institute'),
        ('Meru tech', 'Meru Technical Institute'),
        ('meru_technical_institute', 'Meru Technical Institute'),
        ('mfangano_vtc', 'Mfangano VTC'),
        ('Mikindani Catholic Youth Training Centre', 'Mikindani Catholic VTC'),
        ('Mindhine Vocational Training Centre', 'MINDHINE VTC'),
        ('Mindhine vocational training centre', 'MINDHINE VTC'),
        ('Mindhine VTC', 'MINDHINE VTC'),
        ('mindhine_vyc', 'MINDHINE VTC'),
        ('Mjengo Girl', 'Mjengo Girl'),
        ('MKWAJUNI VTI', 'Mkwajuni VTI'),
        ('MOHI', 'MOHI vtc'),
        ('Molo Technical College', 'Molo Vocational Training College'),
        ('Molo Vocational Training College', 'Molo Vocational Training College'),
        ('molo_vocational_training', 'Molo Vocational Training College'),
        ('mraru_vtc', 'Mraru VTC'),
        ('mselia_vtc', 'Mselia VTC'),
        ('mtongwe_vocational', 'MTONGWE VOCATIONAL TRAINING CENTER'),
        ('Mubere VTC', 'Mubere VTI'),
        ('Mucii Wa Urata', 'Mucii wa Urata'),
        ('Mucii wa Urata', 'Mucii wa Urata'),
        ('MUCII WA URATA', 'Mucii wa Urata'),
        ('Mucii wa urata polytechnic', 'Mucii wa Urata'),
        ('Mucii Wa Urata VTC', 'Mucii wa Urata'),
        ('mucii_wa_urata', 'Mucii wa Urata'),
        ('mudete', 'Mudete'),
        ('MUDETE', 'Mudete'),
        ('MUFULE', 'Mufule TTI'),
        ('MUGEN', 'Mugen VTC'),
        ('Mugondoi', 'Mugondoi VTC'),
        ('MUHUDU', 'Muhundu VTC'),
        ('Mukiiria technical training institute', 'Mukiria Technical Institute'),
        ('Mukiria polytechnic', 'Mukiria Technical Institute'),
        ('Mukiria T.T.I', 'Mukiria Technical Institute'),
        ('Mukiria technical', 'Mukiria Technical Institute'),
        ('MUKIRIA TECHNICAL TRAINING INSTITUTE', 'Mukiria Technical Institute'),
        ('Mukiria Technical Training Institute', 'Mukiria Technical Institute'),
        ('Mukiria technical training institute', 'Mukiria Technical Institute'),
        ('mukiria_technical_institute', 'Mukiria Technical Institute'),
        ('Mukurwe-ini', 'Mukurweini TTI'),
        ('Mukurweini', 'Mukurweini TTI'),
        ('Mukurweini Technical', 'Mukurweini TTI'),
        ('Mukurweini TTI', 'Mukurweini TTI'),
        ('mukurweini_tti', 'Mukurweini TTI'),
        ('MUMBETSA', 'Mumbetsa County Polytechnic'),
        ('mumbetsa_county_polytechnic', 'Mumbetsa County Polytechnic'),
        ('Mumbuni Engineering and Driving school', 'Mumbuni Engineering and Driving School'),
        ('mumbuni_engineering_driving', 'Mumbuni Engineering and Driving School'),
        ('mumias_west', 'Mumias West'),
        ('MUNGATSI TTI', 'Mungatsi vtc'),
        ('MUNGATSI TVC', 'Mungatsi vtc'),
        ('MUSAKASA', 'Musakasa TTI'),
        ('musakasa_tti', 'Musakasa TTI'),
        ('MUYEYE VTI', 'Muyeye vtc'),
        ('Mwala Technical and Vocational College', 'Mwala Technical and Vocational College'),
        ('mwala_technical_vocational', 'Mwala Technical and Vocational College'),
        ('MWAMBEBA', 'Mwambeba vtc'),
        ('mwambeba_ vtc', 'Mwambeba vtc'),
        ('MWAMUTSUNGA VTI', 'Mwamutsunga vtc'),
        ('Mwea Technical and Vocational College', 'Mwea Technical and Vocational College'),
        ('Mwea TVC', 'Mwea Technical and Vocational College'),
        ('mwea_technical', 'Mwea Technical and Vocational College'),
        ('MWEMBENI VTI', 'Mwembeni vtc'),
        ('Naisambu VTC', 'Naisambu vtc'),
        ('Nale', 'NALE COLLEGE'),
        ('NALE COLLEGE', 'NALE COLLEGE'),
        ('nale_college', 'NALE COLLEGE'),
        ('NAMBALE', 'Nambale Polytechnic'),
        ('NANGINA', 'NANGINA VTC'),
        ('nangina_vtc', 'NANGINA VTC'),
        ('nawili_vtc', 'Nawili VTC'),
        ('Ndere Vocaational Training Centre', 'NDERE VTC'),
        ('Ndere Vocational Training Centre', 'NDERE VTC'),
        ('Ndere VTC', 'NDERE VTC'),
        ('ndere_vocational_training_centre', 'NDERE VTC'),
        ('Ndira VTC', 'Ndira VTC'),
        ('Nduluku VTC', 'Nduluku CTTI'),
        ('nduluku_ctti', 'Nduluku CTTI'),
        ('Nesbony College', 'Nesbony College'),
        ('nesbony_college', 'Nesbony College'),
        ('Ng''iya', 'NG''IYA VTC'),
        ('NG''IYA VTC', 'NG''IYA VTC'),
        ('ng''iya_technical_training_institute', 'NG''IYA VTC'),
        ('Ngisiru VTC', 'Ngisiru VTC'),
        ('ngisiru_ngisiru', 'Ngisiru VTC'),
        ('Ngiya Vocational Training Center', 'NG''IYA VTC'),
        ('Ngiya Vocational Training Centre', 'NG''IYA VTC'),
        ('Nyaburumbasi vocational training institute', 'Nyaburumbasi VTI'),
        ('Nyakach TTI', 'Nyakach TTI'),
        ('NYAKACH TTI', 'Nyakach TTI'),
        ('Nyakach Vocational Institute', 'Nyakach TTI'),
        ('nyakach_technical_training_institute', 'Nyakach TTI'),
        ('NYANG''OMA TTI', 'Nyangoma VTC'),
        ('NYANGOMA VTC', 'Nyangoma VTC'),
        ('NYAORE', 'Nyaore Youth Polytechnic'),
        ('Nyaore Youth Polytechnic', 'Nyaore Youth Polytechnic'),
        ('nyaore_youth_polytechnic', 'Nyaore Youth Polytechnic'),
        ('nyeri_nnp', 'Nyeri NNP'),
        ('NZALWA', 'Nzalwa polytechnic'),
        ('nzalwa_ polytechnic', 'Nzalwa polytechnic'),
        ('Old Mathare', 'Old Mathare vtc'),
        ('OLD MATHARE', 'Old Mathare vtc'),
        ('OLYMPIC VOCATIONAL', 'Olympic Vocational'),
        ('Olympic VTC', 'Olympic Vocational'),
        ('olympic_vocational', 'Olympic Vocational'),
        ('OMUGA', 'Omuga VTC'),
        ('Omuga VTC', 'Omuga VTC'),
        ('omuga_vtc', 'Omuga VTC'),
        ('PALAZOLO NAIROBI', 'Palazollo'),
        ('PAUL MBOYA', 'Paul Mboya VTC'),
        ('Paul Mboya VTC', 'Paul Mboya VTC'),
        ('paul_mboya_vtc', 'Paul Mboya VTC'),
        ('PC KINYANJUI', 'PC Kinyanjui'),
        ('PCEA', 'PCEA Emmanuel VTI'),
        ('PCEA EMMANUEAL', 'PCEA Emmanuel VTI'),
        ('PCEA EMMANUEL', 'PCEA Emmanuel VTI'),
        ('pcea_emmanuel_vti', 'PCEA Emmanuel VTI'),
        ('PWANI VTI', 'Pwani VTI'),
        ('Rangala VTC', 'Rang''ala vti'),
        ('Rangwe Technical and Vocational Training College', 'Rangwe VTC'),
        ('Rangwe VTC', 'Rangwe VTC'),
        ('rangwe_vtc', 'Rangwe VTC'),
        ('Rarieda VTC', 'Rarieda VTC'),
        ('rarieda_training_and_resource_centre', 'Rarieda Training and resources center (Rafiki wa Maendeleo)'),
        ('rarieda_vtc', 'Rarieda VTC'),
        ('Riamukuwre', 'Riamukuwre'),
        ('Roka vocational centre', 'Roka vocational centre'),
        ('ROKA VTI', 'Roka vocational centre'),
        ('roka_vocational', 'Roka vocational centre'),
        ('ROTARY VTC', 'Rotary VTC'),
        ('Rotary VTC', 'Rotary VTC'),
        ('rotary_vtc', 'Rotary VTC'),
        ('ruruma_vocational', 'Ruruma Vocational training'),
        ('SABAKO VTC', 'Sabako VTC'),
        ('Sega Vocational', 'SEGA VTC'),
        ('Sega Vocational and Training Centre', 'SEGA VTC'),
        ('Sega Vocational Training Centre', 'SEGA VTC'),
        ('Sega Vocational.', 'SEGA VTC'),
        ('SEGA VTC', 'SEGA VTC'),
        ('Sega VTI', 'SEGA VTC'),
        ('sega_vtc', 'SEGA VTC'),
        ('SEME TTI', 'SEME TTI'),
        ('seme_vocational_training_centre', 'SEME TTI'),
        ('SEREM', 'Serem VTC'),
        ('SERO', 'Sero VTC'),
        ('Sero VTC', 'Sero VTC'),
        ('sero_vtc', 'Sero VTC'),
        ('shilolavakhali_county_polytechnic', 'Shilolavakhali County Polytechnic'),
        ('SIANDA VTC', 'Sianda vtc'),
        ('siaya_tti', 'Siaya TTI'),
        ('Sikri Vocational', 'Sikri VTC'),
        ('Sikri vocational', 'Sikri VTC'),
        ('Sikri VTC', 'Sikri VTC'),
        ('sikri_vtc', 'Sikri VTC'),
        ('Sinyerere VTC', 'Sinyere VTI'),
        ('SIRWAYALA', 'Sirwanyala VTC'),
        ('Sitatunga VTC', 'Sitatunga VTC'),
        ('Skills Centre', 'The Skills Center Malaa'),
        ('SOKONI VTI', 'Sokoni vti'),
        ('sokoni_vti', 'Sokoni vti'),
        ('SOLONGO', 'Solongo VTC'),
        ('sot_tti', 'SOT TTI'),
        ('Springs Jubille Vocational College', 'Springs jubilee'),
        ('ST CHARLES LWANGA', 'St.Charles Lwanga'),
        ('ST JOSEPH VTC KAPLAMAI', 'ST JOSEPH KAPLAMAI VTC'),
        ('St Mathias Mulumba Training College', 'St. Mathias Mulumba Training College'),
        ('ST PAUL SHIANDA', 'St. Paul Shianda'),
        ('ST TERESA', 'Kabula vtc'),
        ('ST TERESA KABULA', 'Kabula vtc'),
        ('st_charles_lwanga', 'St.Charles Lwanga'),
        ('st_joseph_kaplamai', 'ST JOSEPH KAPLAMAI VTC'),
        ('st_kizito_vtc', 'St.Kizito VTC'),
        ('st_lumumba_vocational', 'St. Mathias Mulumba Training College'),
        ('st_marys_polytechnic_kambaa', 'ST. Mary''s Polytechnic, Kambaa'),
        ('st_peters_emulakha', 'St. Peters Emulakha'),
        ('st_teresa_malava', 'St. Teresa Malava'),
        ('ST. JOSEPHS KAPLAMAI VOCATIONAL', 'ST JOSEPH KAPLAMAI VTC'),
        ('ST. Josephs Nyangoma VTC', 'St.Joseph Nyangoma'),
        ('St.Charles Lwanga', 'St.Charles Lwanga'),
        ('ST.PETER''S EMULAKHA', 'St. Peters Emulakha'),
        ('Tausa VTC', 'Tausa Vocational Training Center'),
        ('TAUSA VTC', 'Tausa Vocational Training Center'),
        ('tausa_vocational_training', 'Tausa Vocational Training Center'),
        ('Tetu', 'Tetu technical'),
        ('Tetu Technical', 'Tetu technical'),
        ('Tetu technical', 'Tetu technical'),
        ('Tetu TVC', 'Tetu technical'),
        ('tetu_technical', 'Tetu technical'),
        ('The Skills Center Malaa', 'The Skills Center Malaa'),
        ('the_skills_center', 'The Skills Center Malaa'),
        ('Ugunja TTI', 'Ugunja TTI'),
        ('Ugunja Vocational', 'Ugunja TTI'),
        ('Ugunja Vocational Training Centre', 'Ugunja TTI'),
        ('ugunja_tti', 'Ugunja TTI'),
        ('Ujuzi Institute-CAPYEI Mombasa', 'Ujuzi Institute-CAPYEI Mombasa'),
        ('ujuzi_institute_capyei_kisumu', 'Ujuzi Institute CAP-YEI Kisumu'),
        ('ujuzi_institute_capyei_mombasa', 'Ujuzi Institute-CAPYEI Mombasa'),
        ('ujuzi_institute_capyei_nairobi', 'Ujuzi Institute -CAPYEI -Nairobi'),
        ('Velndale vocational training centre', 'Velndale vacational training centre'),
        ('velndale_vocational_training', 'Velndale vacational training centre'),
        ('Vera college', 'Vera Beauty Technical College'),
        ('Vera College', 'Vera Beauty Technical College'),
        ('Vera Technical College', 'Vera Beauty Technical College'),
        ('vera_beauty_technical', 'Vera Beauty Technical College'),
        ('VISION', 'VISION EMPORMENT TRAINING INSTITUTE'),
        ('VISION EMPORMENT TRAINING INSTITUTE', 'VISION EMPORMENT TRAINING INSTITUTE'),
        ('VISION EMPOWERMENT TRAINING', 'VISION EMPORMENT TRAINING INSTITUTE'),
        ('VISION EMPOWERMENT TRAINING INSTITUTE', 'VISION EMPORMENT TRAINING INSTITUTE'),
        ('Vision impowerment', 'VISION EMPORMENT TRAINING INSTITUTE'),
        ('vision_empowerment_institute', 'VISION EMPORMENT TRAINING INSTITUTE'),
        ('VITE H', 'Viteck Training Institute'),
        ('VITECH', 'Viteck Training Institute'),
        ('Vitech Training College', 'Viteck Training Institute'),
        ('Viteck Training Institute', 'Viteck Training Institute'),
        ('viteck_training', 'Viteck Training Institute'),
        ('Voi Vocational Training Center', 'Voi Vocational Training Centre'),
        ('voi VTC', 'Voi Vocational Training Centre'),
        ('Voi VTC', 'Voi Vocational Training Centre'),
        ('VOI VTC', 'Voi Vocational Training Centre'),
        ('voi_vocational_training', 'Voi Vocational Training Centre'),
        ('Waithaka TVET', 'Waithaka TVET'),
        ('WAITHAKA VTC', 'Waithaka TVET'),
        ('Waithaka VTC', 'Waithaka TVET'),
        ('waithaka_tvet', 'Waithaka TVET'),
        ('wanga_vtc', 'Wanga VTC'),
        ('WEBUYE WEST', 'Webuye west vtc'),
        ('webuye_west_vtc', 'Webuye west vtc'),
        ('welekekha_vtc', 'Welekekha VTC'),
        ('WEST ISUKHA', 'West Isukha'),
        ('West Ugenya VTC', 'West Ugenya Vocational Training Centre'),
        ('west_ugenya_vocational', 'West Ugenya Vocational Training Centre'),
        ('YMCA', 'YMCA -Nairobi'),
        ('YMCA -Nairobi', 'YMCA -Nairobi'),
        ('ymca_Nairobi', 'YMCA -Nairobi'),
        ('Zyara School of Hospitality', 'Zyara School of Hospitality'),
        ('zyara_school_hospitality', 'Zyara School of Hospitality')
    ) as t(old_institution, institution_name)
)

select
    case_id,
    date_of_registration,
    pp_unique_id,
    pp_fullname,
    profession_of_facilitator_psr,
    psychosocial_facilitator_psr,
    gender,
    nationality,
    refugee_type,
    kenyan_national_id_number_dir,
    case
        when county is null or trim(county) = '' then null
        else
            case
                when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'kiii' then 'Kilifi'
                when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'buia' then 'Busia'
                when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'homabay' then 'Homa Bay'
                when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'kiumu' then 'Kisumu'
                when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'mombaa' then 'Mombasa'
                when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'uaingihu' then 'Uain Gihu'
                when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'trannzoia' then 'Tran Nzoia'
                when lower(regexp_replace(county, '[\\s_/-]+', '', 'g')) = 'taitataveta' then 'Taita Taveta'
                else initcap(regexp_replace(county, '[\\s_/-]+', '', 'g'))
            end
    end as county,
    case
        when subcounty is null or trim(subcounty) = '' then null
        else initcap(regexp_replace(subcounty, '[\\s_/-]+', '', 'g'))
    end as subcounty,
    case
        when ward is null or trim(ward) = '' then null
        else initcap(regexp_replace(ward, '[\\s_/-]+', '', 'g'))
    end as ward,
    coworking_county_csr,
    coworking_subcounty_csr,
    coworking_ward_csr,
    primary_phone_number,
    phone_last_8_digits,
    case when is_pwd is null or trim(is_pwd) = '' then null else initcap(is_pwd) end as is_pwd,
    nullif(trim(type_of_disability_dir), '') as type_of_disability_dir,
    case
        when is_young_mother is null or trim(is_young_mother) = '' then null
        when lower(trim(is_young_mother)) = 'yes' then 'yes'
        when lower(trim(is_young_mother)) = 'no' then 'no'
        when lower(trim(is_young_mother)) = 'don''t know' then 'don''t know'
        else lower(trim(is_young_mother))
    end as is_young_mother,
    apprenticeship_provider_apr,
    d.skill_enrolled_apr,
    placement_date_apr,
    grant_amount_bg,
    date_grant_allocated_bg,
    type_of_business_you_operate_bga,
    mark_the_location_of_the_business_raw,
    business_latitude,
    business_longitude,
    business_altitude,
    business_accuracy,
    gps_of_business_location_apbl_raw,
    apprenticeship_latitude,
    apprenticeship_longitude,
    apprenticeship_altitude,
    apprenticeship_accuracy,
    location_of_institution_ttia_raw,
    tvet_latitude,
    tvet_longitude,
    tvet_altitude,
    tvet_accuracy,
    digital_literacy_dl,
    start_date_dl,
    advanced_it_start_date_dl,
    advanced_it_completion_date_dl,
    completion_date_dl,
    final_exams_tc,
    dignity_package_helpful_dka,
    how_helpful_course,
    how_helpful_course_tc,
    how_helpful_was_upskilling_uc,
    why_not_helpful_tc,
    why_not_helpful_uc,
    how_helpful_course_tvet,
    recommend_training_tvet,
    start_date_ent,
        completion_date_ent,
        interest_in_sales_work_ent,
    start_date_int,
    completion_date_int,
    income_on_average_pl,
    placement_opportunity_pl,
    date_first_visit_bm,
    date_of_second_visit_bm,
    date_of_visit_csf,
    date_of_visit_csr,
    date_of_birth_csf,
    age_in_years_csf,
    first_name_csf,
    second_name_csf,
    how_many_csf,
    time_in_csf,
    time_in_csr,
    time_out_csf,
    time_out_csr,
    using_coworking_for_a_living_csr,
    using_coworking_to_earn_a_living_csf,
    what_visitor_is_using_csf,
    what_visitor_is_using_csr,
    purpose_for_using_csf,
    coworking_space_facility,
    swep_handcraft_center_hc,
    start_date_hc,
    completion_date_hc,
    handcraft_training_type_hc,
    swep_iga_center_iga,
    start_date_iga,
    completion_date_iga,
    training_type_iga,
    swep_tailoring_center_st,
    start_date_of_training_st,
    expected_end_date_of_training_st,
    training_session_st,
    coalesce(i.institution_name, d.old_institution) as name_of_institution_tvet,
    name_of_facilitator,
    course_enrolled_tvet,
    start_date_tvet,
    completion_date_tvet,
    nita_exams,

    m.skill_name,
    m.sector_name
from deduplicated_cases d
left join skill_sector_mapping m
    on d.skill_enrolled_apr = m.skill_enrolled_apr
left join institution_name_mapping i
    on lower(trim(d.old_institution)) = lower(trim(i.old_institution))