name: Our first dbt PR job

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 1: Set up SSH
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 2: Establish SSH tunnel
      - name: Establish SSH tunnel
        run: |
          ssh -fN \
            -L 5432:${{ secrets.DB_HOST }}:5432 \
            ${{ secrets.DB_USER }}@${{ secrets.SSH_HOST }}

      - name: Install requirements
        run: pip install -r requirements.txt  

      - name: Install dbt dependencies
        run: dbt deps

      - name: dbt build
        run: dbt build --full-refresh --profiles-dir ./
        env:
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: 127.0.0.1 # Use localhost since we are tunneling via SSH
      
      - name: Benchmarking models
        run: "sqlfluff lint models --bench"
  
      - name: Lint models
        run: "sqlfluff lint models -f human"
